// src/app/windows/project/components/viewport/components/CameraBar.jsx
import styles from "../styles/SideOptions.module.css"
import {Button, Dropdown, DropdownOption, DropdownOptions, Icon, ToolTip} from "@f-ui/core"
import React, {useContext, useMemo, useState} from "react"
import {handleGrab} from "../utils/transform-camera"
import CameraGizmo from "./CameraGizmo"
import useLocalization from "../../../../global/useLocalization"
import updateCameraPlacement from "../utils/update-camera-placement"
import SettingsProvider from "../../../context/SettingsProvider"

export default function CameraBar() {
    const [cameraIsOrtho, setCameraIsOrtho] = useState(false)
    const cameraIcon = useMemo(() => {
        if (!cameraIsOrtho)
            return (
                <div
                    style={{width: "20px", height: "20px", perspective: "40px", transformStyle: "preserve-3d"}}>
                    <Icon
                        styles={{fontSize: "1.1rem", transform: "rotateX(45deg)"}}
                    >grid_on</Icon>
                </div>
            )
        else
            return <Icon styles={{fontSize: "1rem"}} >grid_on</Icon>
    }, [cameraIsOrtho])


    const translate = useLocalization("PROJECT", "VIEWPORT")
    const settings = useContext(SettingsProvider)
    return (
        <div className={styles.cameraWrapper} style={{right: settings.visible.sideBarViewport ? "25px" : "0"}}>
            <CameraGizmo />
            <div
                style={{
                    display: "grid",
                    gap: "2px"
                }}>
                <Dropdown
                    hideArrow={true}
                    className={styles.groupItemVert}
                >
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        Camera position
                    </ToolTip>
                    <Icon styles={{fontSize: "1.1rem"}} >videocam</Icon>
                    <DropdownOptions>
                        <DropdownOption
                            option={{
                                label: translate("TOP"),
                                onClick: () => updateCameraPlacement(0, Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("BOTTOM"),
                                onClick: () => updateCameraPlacement(0, -Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("LEFT"),
                                onClick: () => updateCameraPlacement(Math.PI , 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("RIGHT"),
                                onClick: () => updateCameraPlacement(0,0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("FRONT"),
                                onClick: () =>  updateCameraPlacement(Math.PI /2, 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("BACK"),
                                onClick: () =>  updateCameraPlacement(Math.PI * 1.5, 0)
                            }}/>
                    </DropdownOptions>
                </Dropdown>

                <Button
                    className={styles.groupItemVert}
                    onClick={() => {
                        const negated = !window.renderer.camera.ortho
                        window.renderer.camera.ortho = negated
                        window.renderer.camera.updateProjection()
                        setCameraIsOrtho(negated)
                    }}>
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        {translate("SWITCH_PROJECTION")}
                    </ToolTip>
                    {cameraIcon}
                </Button>

                <div
                    style={{
                        display: "grid",
                        transform: "translateY(12px)",
                        gap: "2px"
                    }}
                >

                    <div
                        className={[styles.groupItemVert, styles.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 0)}
                    >
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            {translate("DRAG_X_ZOOM")}
                        </ToolTip>
                        <Icon >zoom_in</Icon>
                    </div>
                    <div
                        className={[styles.groupItemVert, styles.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 1)}
                        onDoubleClick={() => {
                            window.renderer.camera.centerOn = [0, 0, 0]
                            window.renderer.camera.updateViewMatrix()
                        }}>
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            <div>{translate("DRAG_X_DIR")}</div>
                            <div>{translate("DRAG_Y_DIR")}</div>
                            <div>{translate("DOUBLE_CLICK")}</div>
                        </ToolTip>
                        <Icon >back_hand</Icon>
                    </div>
                </div>
            </div>
        </div>
    )

}

// src/app/windows/project/components/viewport/components/columns/CameraBar.svelte
<script>
    import {handleGrab} from "../../utils/transform-camera"
    import updateCameraPlacement from "../../utils/update-camera-placement"
    import Icon from "../../../../../../components/Icon/Icon.svelte";
    import Dropdown from "../../../../../../components/dropdown/Dropdown.svelte";
    import ToolTip from "../../../../../../components/tooltip/ToolTip.svelte";
    import CAMERA_GIZMO from "../../../../data/misc/CAMERA_GIZMO"
    import {onDestroy, onMount} from "svelte";
    import RendererStoreController from "../../../../stores/RendererStoreController";
    import CameraAPI from "../../../../libs/engine/libs/apis/CameraAPI";
    import CameraTracker from "../../../../libs/engine-extension/libs/CameraTracker";

    export let translate
    let cameraIsOrtho = false
    let requested = false

    onMount(() => {
        CameraTracker.gizmoReference = document.getElementById(CAMERA_GIZMO)
        CameraTracker.update()
    })

    let settings = {}
    const unsubscribeSettings = RendererStoreController.getSettings(v => settings = v)
    onDestroy(() => unsubscribeSettings())

    const onMouseMove = ({currentTarget, movementX, movementY}) => {
        if (currentTarget.isFocused) {
            if (!requested) {
                requested = true
                currentTarget.requestPointerLock()
            }
            if (movementY < 0)
                CameraTracker.pitch += .01 * Math.abs(movementY)
            else if (movementY > 0)
                CameraTracker.pitch -= .01 * Math.abs(movementY)

            if (movementX > 0)
                CameraTracker.yaw += .01 * Math.abs(movementX)
            else if (movementX < 0)
                CameraTracker.yaw -= .01 * Math.abs(movementX)

            CameraTracker.update()

        }
    }
    const onMouseUp = ({currentTarget}) => {
        currentTarget.isFocused = false
        requested = false
    }
</script>

<div class={"wrapper"} style={settings.visible.sideBarViewport ? "right: 25px" : undefined}>


    <div
            class={"gizmo-wrapper"}
            on:mousedown={({currentTarget}) => currentTarget.isFocused = true}
            on:mouseup={onMouseUp}
            on:mousemove={onMouseMove}
    >
        <div class={"camera-view"}>
            <div class={"cube"} id={CAMERA_GIZMO}>
                <div
                        class={"face front"}
                        style="background: hsl(205, 100%, var(--brightness))"
                        on:click={() => updateCameraPlacement(Math.PI / 2, 0)}
                >
                    Z+
                </div>
                <div
                        class={"face back darker"}
                        style="background: hsl(205, 100%, var(--brightness))"
                        on:click={() => updateCameraPlacement(Math.PI * 1.5, 0)}
                >
                    Z-
                </div>
                <div
                        class={"face right"}
                        style="background: hsl(0, 100%, var(--brightness))"
                        on:click={() => updateCameraPlacement(0, 0)}
                >
                    X+
                </div>
                <div
                        class={"face left darker"}
                        style="background: hsl(0, 100%, var(--brightness))"
                        on:click={() => updateCameraPlacement(Math.PI, 0)}
                >
                    X-
                </div>
                <div
                        class={"face top darker"}
                        style="background: hsl(120, 88%, var(--brightness))"
                        on:click={() => updateCameraPlacement(0, Math.PI / 2)}

                >
                    Y-
                </div>
                <div
                        class={"face bottom"}
                        style="background: hsl(120, 88%, var(--brightness))"
                        on:click={() => updateCameraPlacement(0, -Math.PI / 2)}
                >
                    Y+
                </div>
            </div>
        </div>
    </div>

    <Dropdown noBackground={true} hideArrow={true}>
        <button slot="button" class="option">
            <Icon>videocam</Icon>
            <ToolTip>
                Camera position
            </ToolTip>
        </button>

        <button on:click={() => updateCameraPlacement(0, Math.PI /2)}>
            {translate("TOP")}
        </button>
        <button on:click={() => updateCameraPlacement(0, -Math.PI /2)}>
            {translate("BOTTOM")}
        </button>
        <button on:click={() => updateCameraPlacement(Math.PI, 0)}>
            {translate("LEFT")}
        </button>
        <button on:click={() => updateCameraPlacement(0, 0)}>
            {translate("RIGHT")}
        </button>
        <button on:click={() => updateCameraPlacement(Math.PI/2, 0)}>
            {translate("FRONT")}
        </button>
        <button on:click={() => updateCameraPlacement(Math.PI * 1.5, 0)}>
            {translate("BACK")}
        </button>
    </Dropdown>

    <button
            on:click={() => {
                const negated = !CameraAPI.isOrthographic
                CameraAPI.isOrthographic = negated
                CameraAPI.updateProjection()
                cameraIsOrtho  = negated
            }}
            class="option"
    >
        <ToolTip>
            {translate("SWITCH_PROJECTION")}
        </ToolTip>
        {#if !cameraIsOrtho}
            <div style="width: 20px; height: 20px; perspective: 40px; transform-style: preserve-3d">
                <Icon styles="transform: rotateX(45deg)">grid_on</Icon>
            </div>
        {:else}
            <Icon styles="font-size: 1rem">grid_on</Icon>
        {/if}
    </button>

    <div class="option" on:mousedown={e => handleGrab(e, 0)}>
        <ToolTip>
            {translate("DRAG_X_ZOOM")}
        </ToolTip>
        <Icon>zoom_in</Icon>
    </div>
    <div
            class="option"
            on:mousedown={e => handleGrab(e,  1)}
            on:dblclick={() => {
                CameraTracker.centerOn = [0, 0, 0]
                CameraTracker.update()
            }}>
        <ToolTip>
            <div>{translate("DRAG_X_DIR")}</div>
            <div>{translate("DRAG_Y_DIR")}</div>
            <div>{translate("DOUBLE_CLICK")}</div>
        </ToolTip>
        <Icon>back_hand</Icon>
    </div>

</div>


<style>
    .wrapper {
        display: grid;
        align-items: flex-start;
        justify-content: center;
        justify-items: center;

        gap: 2px;
        height: fit-content;
        transition: 150ms ease-in;
        position: absolute;
        right: 0;
        top: 2px;
        z-index: 15;

    }

    .option {
        width: 27px;
        height: 27px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--pj-background-secondary);
        cursor: pointer;
    }

    .option:active {
        color: var(--pj-accent-color);
        border-color: var(--pj-accent-color);
    }


    .gizmo-wrapper {
        overflow: hidden;
        border-radius: 50%;
        padding: 4px;
        transition: 150ms linear;
        border: var(--pj-transparent-border) 1px solid;
    }

    .gizmo-wrapper:hover {
        background: rgb(255 255 255 / 25%);
    }

    .gizmo-wrapper:active {
        cursor: none;
        background: rgb(255 255 255 / 50%);
    }

    .camera-view {
        --cube-size: 25px;

        width: calc(var(--cube-size) * 2);
        height: calc(var(--cube-size) * 2);
        transform: scale3d(1.5, 1.5, 1.5);
        perspective: calc(var(--cube-size) * 2);
    }

    .cube {
        width: calc(var(--cube-size) * 2);
        height: calc(var(--cube-size) * 2);
        position: relative;
        transform-style: preserve-3d;
        transform: translateZ(calc(var(--cube-size) * -3));
    }

    .face {
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
        font-size: 0.8rem;
        font-weight: 900 !important;
        border: transparent 1px solid;
        position: absolute;
        width: var(--cube-size);
        height: var(--cube-size);
        border-radius: 50%;
        text-align: center;

        --brightness: 45%;
    }

    .face:hover {
        border-color: darkorange;
        border-width: 2px;

        --brightness: 50%;
    }

    .front {
        transform: rotateY(0deg) translateZ(var(--cube-size)) translateX(50%) translateY(50%);
    }

    .back {
        transform: rotateY(180deg) translateZ(var(--cube-size)) translateX(-50%) translateY(50%);
    }

    .left {
        transform: rotateY(-90deg) translateZ(calc(var(--cube-size) * 0.5)) translateY(50%);
    }

    .right {
        transform: rotateY(90deg) translateZ(calc(var(--cube-size) * 1.5)) translateY(50%);
    }

    .bottom {
        transform: rotateX(90deg) translateZ(calc(var(--cube-size) * 0.5)) translateX(50%);
    }

    .top {
        transform: rotateX(-90deg) translateZ(calc(var(--cube-size) * 1.5)) translateX(50%);
    }

    .darker {
        color: transparent;
    }

    .darker:hover {
        color: var(--pj-color-secondary);
    }
</style>
