// src/app/windows/home/components/Card.svelte
<script>
    import EnglishLocalization from "../../../static/EnglishLocalization";
    import Input from "../../../components/input/Input.svelte";
    import Dropdown from "../../../components/dropdown/Dropdown.svelte";
    import Icon from "../../../components/Icon/Icon.svelte";
    import "./css/card.css"
    import FileSystem from "../../../libs/FileSystem";

    const {ipcRenderer, shell} = window.require("electron")

    const translate = (key) => EnglishLocalization.HOME.CARD[key]

    export let open = () => null
    export let data = {meta: {}}
    export let onRename = () => null
    export let onDelete = () => null

    let name = data.meta.name
    let openForChange = false
</script>


<div
        class={"wrapper"}
        data-card={data.id}
>
    <div class={"info"} style="width: 200%">
        {#if openForChange}
            <Input
                placeholder={data.meta.name}
                value={name}
                width="200%"
                setSearchString={v => {
                    name = v
                    onRename(v)
                }}
                onBlur={(changed, v) => {
                    if(changed)
                        onRename(v)
                   openForChange = false
                }}
                onEnter={v => {
                    name = v
                    openForChange = false
                    onRename(v)
                }}
            />
        {:else}
            <strong>{name}</strong>
        {/if}
    </div>
    <div class={"divider"}></div>
    <div class={"info"}>
        <strong>{data.meta.lastModification ? data.meta.lastModification : translate("NEVER")}</strong>
        <small>{translate("LAST_MODIFIED")}</small>
    </div>
    <div class={"divider"}></div>
    <div class={"info"}>
        <strong>{data.meta.creationDate}</strong>
        <small>{translate("CREATION")}</small>
    </div>

    <div class={"divider"}></div>
    <div class={"section"}>
        <button class="button card-home" on:click={() => openForChange = true}>
            <Icon styles="font-size: 1rem">edit</Icon>
        </button>

        <Dropdown hideArrow={true}>
            <button class="button card-home" slot="button">
                <Icon>
                    more_horiz
                </Icon>
            </button>

            <button
                    on:click={() => shell.showItemInFolder(localStorage.getItem("basePath") + "projects" + FileSystem.sep + data.id)}
            >
                <Icon styles={"font-size: 1.1rem"}>folder</Icon>
                {translate("SHOW_IN_EXPLORER")}
            </button>
            <button
                    on:click={() => onDelete()}
            >
                <Icon styles={"font-size: 1.1rem"}>delete_forever</Icon>
                {translate("DELETE")}
            </button>
        </Dropdown>
        <button
                on:click={() => open()}
                class="button card-home"
                style="background: var(--pj-border-primary)"
        >
            <Icon styles={"font-size: 1rem"}>open_in_new</Icon>
        </button>
    </div>
</div>


<style>
    .wrapper {
        position: relative;
        width: 100%;
        border-radius: 3px;
        overflow: hidden;
        transition: 150ms linear;
        padding: 4px;
        color: var(--pj-color-secondary);
        font-size: 0.75rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border: var(--pj-border-primary) 1px solid;
        height: 45px;
    }

    .wrapper:hover {
        background: var(--pj-background-primary);
    }

    .divider {
        max-height: 25px;
        height: 25px;
        width: 1px;
        background: var(--pj-border-primary);
    }

    .wrapper:hover {
        background: var(--pj-background-primary);
    }


    .section {
        width: 400px;
        padding-top: 4px;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        gap: 6px;
        overflow: hidden;
    }


    .info {
        width: 100%;
        padding-left: 4px;
        display: grid;
        align-items: center;
        justify-content: flex-start;
    }

</style>

// src/home/components/Card.jsx
import styles from "../styles/Card.module.css"
import PropTypes from "prop-types"
import {Button, Dropdown, DropdownOption, DropdownOptions, DropdownProvider, Icon, TextField} from "@f-ui/core"
import React, {useContext, useRef, useState} from "react"
import FileSystem from "../../project/libs/FileSystem"
import ROUTES from "../../../public/static/ROUTES"

const {ipcRenderer, shell} = window.require("electron")
export default function Card(props) {
    const {data} = props
    const ref = useRef()
    const [name, setName] = useState(data.meta.name)
    return (
        <div
            className={styles.wrapper}
            data-card={props.data.id}
            ref={ref}
        >
            <div style={{width: "100%", fontSize: ".9rem", fontWeight: 550}}>
                {name}
            </div>
            <div className={styles.divider}/>
            <div style={{width: "100%", paddingLeft: "4px"}}>
                {data.meta.lastModification ? data.meta.lastModification : "Not modified"}
            </div>
            <div className={styles.divider}/>
            <div style={{width: "100%", paddingLeft: "4px"}}>
                {data.meta.creationDate}
            </div>
            <div className={styles.divider}/>
            <div className={styles.section}>
                <Dropdown
                    className={styles.button}
                    wrapperClassname={styles.modalOptions}
                    hideArrow={true}>
                    <Icon styles={{fontSize: "1rem"}}>edit</Icon>
                    <DropdownOptions>
                        <Rename name={name} setName={setName} onRename={props.onRename}/>
                    </DropdownOptions>
                </Dropdown>
                <Dropdown
                    hideArrow={true}
                    className={styles.button}
                >
                    <Icon>
                        more_horiz
                    </Icon>
                    <DropdownOptions>
                        <DropdownOption option={{
                            label: "Show in explorer",
                            icon: <Icon styles={{fontSize: "1.1rem"}}>folder</Icon>,
                            onClick: () => shell.showItemInFolder(localStorage.getItem("basePath") + "projects" + FileSystem.sep + data.id)
                        }}/>
                        <DropdownOption option={{
                            label: "Delete",
                            icon: <Icon styles={{fontSize: "1.1rem"}}>delete_forever</Icon>,
                            onClick: () => props.onDelete()
                        }}/>
                    </DropdownOptions>
                </Dropdown>
                <Button
                    onClick={() => {
                        ipcRenderer.send(ROUTES.SWITCH_MAIN_WINDOW, {
                            windowID: props.data.id,
                            data: props.data,
                            hasMain: false
                        })
                    }}
                    className={styles.button}
                    styles={{background: "var(--pj-border-primary)"}}
                >
                    <Icon styles={{fontSize: "1rem"}}>open_in_new</Icon>
                </Button>
            </div>
        </div>
    )
}
Card.propTypes = {
    isLast: PropTypes.bool,
    index: PropTypes.number,
    data: PropTypes.object,
    onRename: PropTypes.func.isRequired,
    onDelete: PropTypes.func.isRequired,
    variant: PropTypes.oneOf(["row", "cell"])
}

function Rename(props) {
    const {setName, name, onRename} = props
    const dropdownContext = useContext(DropdownProvider)
    return (
        <TextField
            handleChange={e => setName(e)}
            noMargin={true}
            placeholder={"New name"}
            value={name} height={"30px"}
            onEnter={() => {
                onRename(name)
                dropdownContext.setOpen(false)
                alert.pushAlert("Project renamed", "success")
            }}
        />
    )
}

Rename.propTypes={
    setName: PropTypes.func, name: PropTypes.string, onRename: PropTypes.func
}
