// src/windows/home/components/Recent.jsx
import PropTypes from "prop-types"
import React, {useMemo} from "react"
import styles from "../styles/Recent.module.css"
import logo from "../../../static/logo.png"
import useLocalization from "../../../global/useLocalization"

export default function Recent(props) {
    const toShow = useMemo(() => {
        return props.projects.sort((a, b) => {
            if (a.meta?.lastModification < b.meta?.lastModification)
                return -1
            if (a.meta?.lastModification > b.meta?.lastModification)
                return 1
            return 0
        }).slice(0, 5)
    }, [props.projects])

    const translate = useLocalization("HOME", "CARD")

    return (
        <div style={{color: "var(--pj-color-secondary)"}}>
            <h4 style={{marginBottom: "4px", marginTop: "4px"}}>{translate("RECENT")}</h4>

            <div className={styles.wrapper}>

                {toShow.map(project => (
                    <div className={styles.card} key={project.id} onClick={() => props.open(project)}>
                        <div className={styles.preview}>
                            <img
                                draggable={false}
                                src={project.meta.preview ? project.meta.preview : logo}
                                alt={translate("PROJECT")}
                            />
                        </div>
                        <div className={styles.content}>
                            <strong>{project.meta.name}</strong>
                            <small>{project.meta.lastModification ? project.meta.lastModification : translate("NEVER")}</small>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    )
}

Recent.propTypes = {
    projects: PropTypes.array,
    open: PropTypes.func
}

// src/app/windows/home/components/Recent.svelte
<script>
    import EnglishLocalization from "../../../static/EnglishLocalization";
    import logo from "../../../../assets/logo.png"
    export let open = () => null
    export let projects = []
    function getRecent(projects){
        return projects.sort((a, b) => {
            if (a.meta?.lastModification < b.meta?.lastModification)
                return -1
            if (a.meta?.lastModification > b.meta?.lastModification)
                return 1
            return 0
        }).slice(0, 5)
    }
    $: toShow = Array.isArray(projects) ? getRecent( projects ) : []

    const translate = (key) => EnglishLocalization.HOME.CARD[key]
</script>

{#if toShow && toShow.length > 0}
<div style="color: var(--pj-color-secondary)">
    <h4 style="margin-bottom: 4px; margin-top: 4px">{translate("RECENT")}</h4>
    <div class={"wrapper"}>
        {#each toShow as project}
            <div class={"card"} on:click={() => open(project)}>
                <div class={"preview"}>
                    <img
                        draggable="false"
                        src={project.meta.preview ? project.meta.preview : logo}
                        alt={translate("PROJECT")}
                    />
                </div>
                <div class={"content"}>
                    <strong>{project.meta.name}</strong>
                    <small>{project.meta.lastModification ? project.meta.lastModification : translate("NEVER")}</small>
                </div>
            </div>
        {/each}
    </div>
</div>
{/if}



<style>
    .wrapper {
        margin-bottom: 16px;
        display: flex;
        align-items: center;
        gap: 8px;
    }

    .card {
        color: var(--pj-color-secondary);

        border-radius: 5px;
        border: var(--pj-border-primary) 1px solid;
        background: var(--pj-background-tertiary);


        display: flex;
        gap: 4px;
        align-items: center;

        padding: 4px;
        height: 75px;
        width: 225px;

        font-size: .85rem;
        transition: 150ms linear;

        cursor: pointer;
    }
    .card:hover{
        background: var(--pj-background-primary);
    }
    .preview{
        width: 35%;
        max-height: 100%;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .preview > img{
        height: 50px;
    }
    .content{
        display: grid;
        justify-content: flex-start;
    }
</style>
