// src/app/windows/project/views/component-editor/components/Transform.svelte
import PropTypes from "prop-types"
import React, {useEffect, useState} from "react"
import Transformation from "../../../engine/utils/Transformation"

import Range from "../../../../views/range/Range"
import styles from "../styles/Forms.module.css"

export default function Transform(props) {
    const [state, setState] = useState({})
    const getNewState = () => {
        const euler = props.selected.rotationUpdated ? props.selected.rotation : Transformation.getEuler(props.selected.rotationQuat)
        return {
            xT: props.selected.translation[0],
            yT: props.selected.translation[1],
            zT: props.selected.translation[2],

            xS: props.selected.scaling[0],
            yS: props.selected.scaling[1],
            zS: props.selected.scaling[2],

            xR: euler[0] * 180 / Math.PI,
            yR: euler[1] * 180 / Math.PI,
            zR: euler[2] * 180 / Math.PI,
        }
    }
    useEffect(() => {
        setState(getNewState())
    }, [props])


    return (
        <>
            <label className={styles.label}>Translation</label>
            <Range
                accentColor={"red"}
                variant={"embedded"}
                label={"X"}
                value={state.xT}
                precision={3}
                incrementPercentage={.01}
                onFinish={(v) => {
                    setState({
                        ...state,
                        xT: v
                    })
                }}
                handleChange={e => {
                    props.selected.translation[0] = e
                    props.selected.changed = true
                }}
            />
            <Range
                accentColor={"#00ff00"}
                label={"Y"}
                variant={"embedded"}
                precision={3}
                incrementPercentage={.01}
                value={state.yT}
                onFinish={(v) => {
                    setState({
                        ...state,
                        yT: v
                    })
                }}
                handleChange={e => {
                    props.selected.translation[1] = e
                    props.selected.changed = true
                }}
            />
            <Range
                accentColor={"blue"}
                label={"Z"}
                variant={"embedded"}
                precision={3}
                incrementPercentage={.01}
                value={state.zT}
                onFinish={(v) => {
                    setState({
                        ...state,
                        zT: v
                    })
                    // window.renderer.
                }}
                handleChange={e => {
                    props.selected.translation[2] = e
                    props.selected.changed = true

                }}
            />

            <label className={styles.label} style={{marginTop: "4px"}}>Scaling</label>
            <Range
                disabled={props.selected.lockedScaling}
                accentColor={"red"}
                label={"X"}
                variant={"embedded"}
                value={state.xS}
                minValue={0.001}
                precision={3}

                incrementPercentage={.01}
                onFinish={(v) => {
                    props.submitScaling("x", v)
                }}
                handleChange={e => {
                    props.selected.scaling = [e, props.selected.scaling[1], props.selected.scaling[2]]
                    setState({...state, xS: e})

                }}
            />
            <Range
                disabled={props.selected.lockedScaling}
                accentColor={"#00ff00"}
                label={"Y"}
                variant={"embedded"}
                value={state.yS}
                minValue={0.001}
                precision={3}
                incrementPercentage={.01}
                onFinish={(v) => {
                    props.submitScaling("y", v)
                }}
                handleChange={e => {
                    props.selected.scaling = [props.selected.scaling[0], e, props.selected.scaling[2]]
                    setState({...state, yS: e})

                }}/>
            <Range
                disabled={props.selected.lockedScaling}
                accentColor={"blue"}
                label={"Z"}
                variant={"embedded"}
                value={state.zS}
                minValue={0.001}
                precision={3}
                incrementPercentage={.01}
                onFinish={(v) => {
                    props.submitScaling("z", v)
                }}
                handleChange={e => {
                    props.selected.scaling = [props.selected.scaling[0], props.selected.scaling[1], e]
                    setState({...state, zS: e})

                }}
            />

            <label className={styles.label} style={{marginTop: "4px"}}>Rotation</label>
            <Range
                disabled={props.selected.lockedRotation}
                accentColor={"red"}
                label={"X"}
                variant={"embedded"}
                metric={"angle"}
                value={state.xR}
                onFinish={(v) => {
                    props.submitRotation("x", v * Math.PI / 180)
                }}
                handleChange={e => {
                    props.selected.rotation = [parseFloat(e) * Math.PI / 180, props.selected.rotation[1], props.selected.rotation[2]]
                    setState({...state, xR: parseFloat(e)})
                }}/>
            <Range
                disabled={props.selected.lockedRotation}
                metric={"angle"}
                accentColor={"#00ff00"}
                label={"Y"}
                variant={"embedded"}
                value={state.yR}
                onFinish={(v) => {
                    props.submitRotation("y", v * Math.PI / 180)
                }}
                handleChange={e => {
                    props.selected.rotation = [props.selected.rotation[0], parseFloat(e) * Math.PI / 180, props.selected.rotation[2]]
                    setState({...state, yR: parseFloat(e)})
                }}/>
            <Range
                accentColor={"blue"}
                disabled={props.selected.lockedRotation}
                metric={"angle"}
                label={"Z"}
                variant={"embedded"}
                value={state.zR}
                onFinish={(v) => {
                    props.submitRotation("z", v * Math.PI / 180)
                }}
                handleChange={e => {
                    props.selected.rotation = [props.selected.rotation[0], props.selected.rotation[1], parseFloat(e) * Math.PI / 180]
                    setState({...state, zR: parseFloat(e)})
                }}
            />
        </>
    )
}

Transform.propTypes = {
    entityID: PropTypes.string,

    selected: PropTypes.object,
    submitRotation: PropTypes.func,
    submitTranslation: PropTypes.func,
    submitScaling: PropTypes.func
}

// src/views/scene/forms/TransformComponent.jsx
import PropTypes from "prop-types";
import React, {useContext, useEffect, useState} from "react";
import styles from "../styles/Forms.module.css";
import {Accordion, AccordionSummary} from "@f-ui/core";
import Range from "../../../components/range/Range";
import SettingsProvider from "../../../services/hooks/SettingsProvider";
import Transformation from "../../../services/engine/utils/workers/Transformation";


const toDeg = 57.2957795131
export default function TransformComponent(props) {
    const settings = useContext(SettingsProvider)
    const getNewState = () => {
        const euler = props.selected.rotationUpdated ? props.selected.rotation : Transformation.getEuler(props.selected.rotationQuat)

        return {
            xT: props.selected.translation[0],
            yT: props.selected.translation[1],
            zT: props.selected.translation[2],

            xS: props.selected.scaling[0],
            yS: props.selected.scaling[1],
            zS: props.selected.scaling[2],

            xR: euler[0] * 180 / Math.PI,
            yR: euler[1] * 180 / Math.PI,
            zR: euler[2] * 180 / Math.PI,

        }
    }
    const [state, setState] = useState({})


    useEffect(() => {

        setState(getNewState())
    }, [props])

    const translate = (newValue) => {
        let t = newValue
        props.selected.translation = t
        setState({
            ...state,
            xT: t[0],
            yT: t[1],
            zT: t[2],
        })
    }
    return (
        <>
            <Accordion className={styles.fieldset}>
                <AccordionSummary className={styles.summary}>
                    Translation
                </AccordionSummary>

                <div className={styles.inputs}>
                    <Range
                        metric={'m'}
                        accentColor={'red'}
                        label={'x'}
                        value={state.xT}
                        precision={3}
                        incrementPercentage={.01}
                        onFinish={() => props.submitTranslation('x', state.xT)}
                        handleChange={e => {
                            translate([parseFloat(e), state.yT, state.zT])
                            // props.selected.translation =
                            // setState({...state, xT: parseFloat(e)})
                        }}
                    />
                    <Range
                        metric={'m'}
                        accentColor={'#00ff00'}
                        label={'y'}
                        precision={3}
                        incrementPercentage={.01}
                        value={state.yT}
                        onFinish={() => props.submitTranslation('y', state.yT)}
                        handleChange={e => {
                            translate([state.xT, parseFloat(e), state.zT])
                            // props.selected.translation =
                            // setState({...state, yT: parseFloat(e)})

                        }}
                    />
                    <Range
                        metric={'m'}
                        accentColor={'#0095ff'}
                        label={'z'}
                        precision={3}
                        incrementPercentage={.01}
                        value={state.zT}
                        onFinish={() => {

                            props.submitTranslation('z', state.zT)
                        }}
                        handleChange={e => {
                            translate([state.xT, state.yT, parseFloat(e)])
                            // props.selected.translation = [state.xT, state.yT, parseFloat(e)]
                            // setState({...state, zT: parseFloat(e)})
                        }}
                    />
                </div>

            </Accordion>
            <Accordion className={styles.fieldset}>
                <AccordionSummary className={styles.summary}>
                    Scale
                </AccordionSummary>
                <div className={styles.inputs}>
                    <Range
                        disabled={props.selected.lockedScaling}
                        accentColor={'red'}
                        label={'x'}
                        value={state.xS}
                        minValue={0.001}
                        precision={3}
                        incrementPercentage={.01}
                        onFinish={() => props.submitScaling('x', state.xS)}
                        handleChange={e => {

                            props.selected.scaling = [e, props.selected.scaling[1], props.selected.scaling[2]]
                            setState({...state, xS: e})

                        }}
                    />
                    <Range
                        disabled={props.selected.lockedScaling}
                        accentColor={'#00ff00'}
                        label={'y'}
                        value={state.yS}
                        minValue={0.001}
                        precision={3}
                        incrementPercentage={.01}
                        onFinish={() => props.submitScaling('y', state.yS)}
                        handleChange={e => {

                            props.selected.scaling = [props.selected.scaling[0], e, props.selected.scaling[2]]
                            setState({...state, yS: e})

                        }}/>
                    <Range
                        disabled={props.selected.lockedScaling}
                        accentColor={'#0095ff'}
                        label={'z'}
                        value={state.zS}
                        minValue={0.001}
                        precision={3}
                        incrementPercentage={.01}
                        onFinish={() => props.submitScaling('z', state.zS)}
                        handleChange={e => {

                            props.selected.scaling = [props.selected.scaling[0], props.selected.scaling[1], e]
                            setState({...state, zS: e})

                        }}
                    />
                </div>
            </Accordion>
            <Accordion className={styles.fieldset}>
                <AccordionSummary className={styles.summary}>
                    Rotation
                </AccordionSummary>
                <div className={styles.inputs}>
                    <Range
                        disabled={props.selected.lockedRotation}
                        accentColor={'red'}
                        label={'x'}
                        metric={'angle'}
                        value={state.xR}
                        onFinish={() => props.submitRotation('x', state.xR * Math.PI / 180)}
                        handleChange={e => {
                            props.selected.rotation = [parseFloat(e) * Math.PI / 180, props.selected.rotation[1], props.selected.rotation[2]]

                            setState({...state, xR: parseFloat(e)})
                        }}/>
                    <Range
                        disabled={props.selected.lockedRotation}
                        metric={'angle'}
                        accentColor={'#00ff00'}
                        label={'y'}
                        value={state.yR}
                        onFinish={() => props.submitRotation('y', state.yR * Math.PI / 180)}
                        handleChange={e => {
                            props.selected.rotation = [props.selected.rotation[0], parseFloat(e) * Math.PI / 180, props.selected.rotation[2]]
                            setState({...state, yR: parseFloat(e)})
                        }}/>
                    <Range
                        accentColor={'#0095ff'}
                        disabled={props.selected.lockedRotation}
                        metric={'angle'}
                        label={'z'}
                        value={state.zR}
                        onFinish={() => props.submitRotation('z', state.zR * Math.PI / 180)}
                        handleChange={e => {
                            props.selected.rotation = [props.selected.rotation[0], props.selected.rotation[1], parseFloat(e) * Math.PI / 180]
                            setState({...state, zR: parseFloat(e)})
                        }}
                    />
                </div>

            </Accordion>
        </>
    )
}

TransformComponent.propTypes = {
    selected: PropTypes.object,
    submitRotation: PropTypes.func,
    submitTranslation: PropTypes.func,
    submitScaling: PropTypes.func
}
