// src/app/windows/project/components/component/components/Rendering.jsx
import React, {useContext, useEffect} from "react"
import SettingsProvider from "../../../context/SettingsProvider"
import {Checkbox} from "@f-ui/core"
import AccordionTemplate from "../../../../components/accordion/AccordionTemplate"
import styles from "../styles/Forms.module.css"
import useDirectState from "../../../../components/hooks/useDirectState"
import Range from "../../../../components/range/Range"

export default function Rendering() {
    const settings = useContext(SettingsProvider)
    const [state] = useDirectState({})
    useEffect(() => {
        state.FXAASpanMax = settings.FXAASpanMax
        state.FXAAReduceMin = settings.FXAAReduceMin
        state.FXAAReduceMul = settings.FXAAReduceMul

        state.shadowMapResolution = settings.shadowMapResolution
        state.shadowAtlasQuantity = settings.shadowAtlasQuantity
        state.pcfSamples = settings.pcfSamples

        state.total_strength = settings.total_strength
        state.base = settings.base
        state.area = settings.area
        state.falloff = settings.falloff
        state.radius = settings.radius
        state.samples = settings.samples

        state.ssgiQuality = settings.ssgiQuality
        state.ssgiBrightness = settings.ssgiBrightness
        state.ssgiStepSize = settings.ssgiStepSize

        state.ssrMaxSteps = settings.ssrMaxSteps
        state.ssrStepSize = settings.ssrStepSize


    }, [])


    return (
        <>
            <AccordionTemplate title={"Resolution"}>
                <Range
                    label={"X"}
                    variant={"embedded"}
                    onFinish={v => settings.resolution = [v, settings.resolution[1]]}
                    incrementPercentage={1}
                    precision={0}
                    handleChange={() => null}
                    value={settings.resolution[0]}
                    minValue={1}
                />
                <Range
                    label={"Y"}
                    variant={"embedded"}
                    onFinish={v => settings.resolution = [settings.resolution[0], v]}
                    incrementPercentage={1}
                    precision={0}
                    handleChange={() => null}
                    value={settings.resolution[1]}
                    minValue={1}
                />
            </AccordionTemplate>
            <Checkbox
                noMargin={true}
                checked={settings.fxaa}
                handleCheck={() => settings.fxaa = !settings.fxaa}
                label={"Anti-aliasing"}
                height={"25px"}
                width={"100%"}/>

            <AccordionTemplate title={"Screen space reflections"}>
                <Checkbox
                    noMargin={true}
                    checked={settings.ssr}
                    handleCheck={() => settings.ssr = !settings.ssr}
                    label={"Enabled"}
                    height={"25px"}
                    width={"100%"}
                />
                <Range
                    disabled={!settings.ssr}
                    label={"Steps"}
                    onFinish={v => settings.ssrMaxSteps = v}
                    incrementPercentage={1}
                    precision={0}
                    minValue={0}
                    maxValue={100}
                    handleChange={v => window.renderer.params.ssrMaxSteps = v}
                    value={state.ssrMaxSteps}
                />
                <Range
                    disabled={!settings.ssr}
                    label={"Step size"}
                    onFinish={v => settings.ssrStepSize = v}
                    incrementPercentage={.001}
                    precision={4}
                    minValue={.05}
                    maxValue={1}
                    handleChange={v => window.renderer.params.ssrStepSize = v}
                    value={state.ssrStepSize}
                />
            </AccordionTemplate>


            <AccordionTemplate title={"Global illumination"}>
                <Checkbox
                    noMargin={true}
                    checked={settings.ssgi}
                    handleCheck={() => settings.ssgi = !settings.ssgi}
                    label={"Enabled"}
                    height={"25px"}
                    width={"100%"}
                />
                <Range
                    disabled={!settings.ssgi}
                    label={"Steps"}
                    onFinish={v => settings.ssgiQuality = v}
                    incrementPercentage={1}
                    precision={0}
                    minValue={0}
                    maxValue={100}
                    handleChange={v => window.renderer.params.ssgiQuality = v}
                    value={state.ssgiQuality}
                />

                <Range
                    disabled={!settings.ssgi}
                    label={"Intensity"}
                    onFinish={v => {
                        settings.ssgiBrightness = v
                        state.ssgiBrightness = v
                    }}
                    incrementPercentage={.001}
                    precision={4}
                    minValue={0}
                    maxValue={10}
                    handleChange={v => {
                        // state.ssgiBrightness = v
                        window.renderer.params.ssgiBrightness = v
                    }}
                    value={state.ssgiBrightness}
                />

                <Range
                    disabled={!settings.ssgi}
                    label={"Step size"}
                    onFinish={v => {
                        settings.ssgiStepSize = v
                        state.ssgiStepSize = v
                    }}
                    incrementPercentage={.001}
                    precision={4}
                    minValue={.05}
                    maxValue={1}
                    handleChange={v => window.renderer.params.ssgiStepSize = v}
                    value={state.ssgiStepSize}
                />

            </AccordionTemplate>
            
            <AccordionTemplate title={"Shadows"}>

                <Range
                    label={"Atlas resolution"}
                    accentColor={"red"}
                    onFinish={v => settings.shadowMapResolution = v}
                    incrementPercentage={1}
                    precision={0}
                    minValue={1}
                    handleChange={v => state.shadowMapResolution = v}
                    value={state.shadowMapResolution}
                />
                <div className={styles.inline}>
                    <Range
                        label={"Lights"}
                        accentColor={"red"}
                        onFinish={v => settings.shadowAtlasQuantity = v}
                        incrementPercentage={1}
                        precision={0}
                        minValue={1}
                        handleChange={v => state.shadowAtlasQuantity = v}
                        value={state.shadowAtlasQuantity}
                    />

                    <Range
                        label={"Smoothing samples"}
                        accentColor={"green"}
                        onFinish={v => settings.pcfSamples = v}
                        incrementPercentage={1}
                        precision={0}
                        minValue={1}
                        maxValue={10}
                        handleChange={v => state.pcfSamples = v}
                        value={state.pcfSamples}
                    />
                </div>
            </AccordionTemplate>

            <AccordionTemplate title={"Ambient occlusion"}>
                <Checkbox
                    noMargin={true}
                    checked={settings.ao}
                    handleCheck={() => settings.ao = !settings.ao}
                    label={"Enabled"}
                    height={"25px"}
                    width={"100%"}/>
                <div className={styles.inline}>
                    <Range
                        disabled={!settings.ao}
                        label={"Strength"}
                        accentColor={"red"}
                        onFinish={v => settings.total_strength = v}
                        incrementPercentage={.001}
                        precision={3}
                        minValue={0}
                        handleChange={v => state.total_strength = v}
                        value={state.total_strength}
                    />
                    <Range
                        disabled={!settings.ao}
                        label={"Base"}
                        accentColor={"green"}
                        onFinish={v => settings.base = v}
                        incrementPercentage={.001}
                        precision={3}
                        minValue={0}
                        handleChange={v => state.base = v}
                        value={state.base}
                    />
                </div>

                <div className={styles.inline}>
                    <Range
                        disabled={!settings.ao}
                        label={"Area"}
                        accentColor={"red"}
                        onFinish={v => settings.area = v}
                        incrementPercentage={.001}
                        precision={3}
                        minValue={0}
                        handleChange={v => state.area = v}
                        value={state.area}
                    />
                    <Range
                        disabled={!settings.ao}
                        label={"Falloff"}
                        accentColor={"green"}
                        onFinish={v => settings.falloff = v}
                        incrementPercentage={.001}
                        precision={3}
                        minValue={0}
                        handleChange={v => state.falloff = v}
                        value={state.falloff}
                    />
                </div>

                <div className={styles.inline}>
                    <Range
                        disabled={!settings.ao}
                        label={"Radius"}
                        accentColor={"red"}
                        onFinish={v => settings.radius = v}
                        incrementPercentage={.001}
                        precision={3}
                        minValue={0}
                        handleChange={v => state.radius = v}
                        value={state.radius}
                    />

                    <Range
                        label={"Samples"}
                        accentColor={"red"}
                        onFinish={v => settings.samples = v}
                        incrementPercentage={1}
                        precision={0}
                        minValue={1} disabled={true}
                        maxValue={10}
                        handleChange={v => state.samples = v}
                        value={state.samples}
                    />
                </div>
            </AccordionTemplate>
        </>
    )
}

// src/frontend/settings/components/Rendering.svelte
<script>
    import Range from "../../components/range/Range.svelte";
    import Accordion from "../../components/accordion/Accordion.svelte";
    import Checkbox from "../../components/checkbox/Checkbox.svelte";
    import Localization from "../../libs/Localization";
    import Engine from "../../../../public/engine/production/Engine";

    export let settings
    export let update

    const translate = (key) => Localization.PROJECT.INSPECTOR[key]

</script>


<Checkbox
        checked={settings.fxaa}
        handleCheck={() => {
               update("fxaa", !settings.fxaa)
        }}
        label={translate("AA")}
/>
<Accordion title={translate("RESOLUTION")}>
    <Range
            label={"X"}
            variant={"embedded"}
            onFinish={v => {
                update("resolution", [v, settings.resolution[1]])
            }}
            incrementPercentage={1}
            precision={0}
            handleChange={() => null}
            value={settings.resolution[0]}
            minValue={1}
    />
    <Range
            label={"Y"}
            variant={"embedded"}
            onFinish={v => {
                update("resolution", [settings.resolution[0], v])
            }}
            incrementPercentage={1}
            precision={0}
            handleChange={() => null}
            value={settings.resolution[1]}
            minValue={1}
    />
</Accordion>

<Accordion title={translate("SSR")}>
    <Checkbox
            checked={settings.ssr}
            handleCheck={() => {
                update("ssr",  !settings.ssr)
            }}
            label={translate("ENABLED")}
    />
    <Range
            disabled={!settings.ssr}
            label={translate("STEPS")}
            onFinish={v => {
                update("ssrMaxSteps", v)

            }}
            incrementPercentage={1}
            precision={0}
            minValue={0}
            maxValue={100}
            handleChange={v => Engine.params.ssrMaxSteps = v}
            value={settings.ssrMaxSteps}
    />
    <Range
            disabled={!settings.ssr}
            label={translate("STEP_SIZE")}
            onFinish={v => {
                update("ssrStepSize", v)
            }}
            incrementPercentage={.001}
            precision={4}
            minValue={.05}
            maxValue={1}
            handleChange={v => Engine.params.ssrStepSize = v}
            value={settings.ssrStepSize}
    />
</Accordion>


<Accordion title={translate("SSGI")}>
    <Checkbox
            checked={settings.ssgi}
            handleCheck={() =>  {
                update("ssgi", !settings.ssgi)
            }}
            label={translate("ENABLED")}
    />
    <Range
            disabled={!settings.ssgi}
            label={translate("STEPS")}
            onFinish={v => {
                    update("ssgiQuality", v)
            }}
            incrementPercentage={1}
            precision={0}
            minValue={0}
            maxValue={100}
            handleChange={v => Engine.params.ssgiQuality = v}
            value={settings.ssgiQuality}
    />

    <Range
            disabled={!settings.ssgi}
            label={translate("STRENGTH")}
            onFinish={v => {
                update("ssgiBrightness", v)
            }}
            incrementPercentage={.001}
            precision={4}
            minValue={0}
            maxValue={10}
            handleChange={v => {
                Engine.params.ssgiBrightness = v
            }}
            value={settings.ssgiBrightness}
    />

    <Range
            disabled={!settings.ssgi}
            label={translate("STEP_SIZE")}
            onFinish={v => {
                update("ssgiStepSize", v)
            }}
            incrementPercentage={.001}
            precision={4}
            minValue={.05}
            maxValue={1}
            handleChange={v => Engine.params.ssgiStepSize = v}
            value={settings.ssgiStepSize}
    />

</Accordion>

<Accordion title={translate("SHADOWS")}>

    <Range
            label={translate("RESOLUTION")}
            accentColor={"red"}
            onFinish={v => {
                update("shadowMapResolution", v)
            }}
            incrementPercentage={1}
            precision={0}
            minValue={1}

            value={settings.shadowMapResolution}
    />
    <div data-inline="-">
        <Range
                label={translate("LIGHTS")}
                accentColor={"red"}
                onFinish={v => {
                    update("shadowAtlasQuantity", v)
                }}
                incrementPercentage={1}
                precision={0}
                minValue={1}

                value={settings.shadowAtlasQuantity}
        />

        <Range
                label={translate("SMOOTHING_SAMPLES")}
                accentColor={"green"}
                onFinish={v => {
                    update("pcfSamples", v)
                }}
                incrementPercentage={1}
                precision={0}
                minValue={1}
                maxValue={10}

                value={settings.pcfSamples}
        />
    </div>
</Accordion>

<Accordion title={translate("AO")}>
    <Checkbox
            checked={settings.ao}
            handleCheck={() => update("ao", !settings.ao)}
            label={translate("ENABLED")}
    />
    <div data-inline="-">
        <Range
                disabled={!settings.ao}
                label={translate("STRENGTH")}
                accentColor={"red"}
                onFinish={v => {
                    update("total_strength", v)
                }}
                incrementPercentage={.001}
                precision={3}
                minValue={0}

                value={settings.total_strength}
        />
        <Range
                disabled={!settings.ao}
                label={translate("BASE")}
                accentColor={"green"}
                onFinish={v => {
                    update("base", v)
                }}
                incrementPercentage={.001}
                precision={3}
                minValue={0}

                value={settings.base}
        />
    </div>

    <div data-inline="-">
        <Range
                disabled={!settings.ao}
                label={translate("AREA")}
                accentColor={"red"}
                onFinish={v => {
                    update("area", v)
                }}
                incrementPercentage={.001}
                precision={3}
                minValue={0}

                value={settings.area}
        />
        <Range
                disabled={!settings.ao}
                label={translate("FALLOFF")}
                accentColor={"green"}
                onFinish={v => {
                    update("falloff", v)
                }}
                incrementPercentage={.001}
                precision={3}
                minValue={0}

                value={settings.falloff}
        />
    </div>

    <div data-inline="-">
        <Range
                disabled={!settings.ao}

                label={translate("RADIUS")}
                accentColor={"red"}
                onFinish={v =>{
                    update("radius", v)
                }}
                incrementPercentage={.001}
                precision={3}
                minValue={0}

                value={settings.radius}
        />

        <Range
                label={translate("SAMPLES")}
                accentColor={"red"}
                onFinish={v => {
                    update("samples", v)
                }}
                incrementPercentage={1}
                precision={0}
                minValue={1} disabled={true}
                maxValue={10}

                value={settings.samples}
        />
    </div>
</Accordion>
