// src/app/windows/project/views/console/Console.svelte
<script>
    import EnglishLocalization from "../../../../static/EnglishLocalization";
    import Header from "../../../../components/view/components/Header.svelte";
    import Icon from "../../../../components/Icon/Icon.svelte";
    import {onDestroy, onMount} from "svelte";

    export let hidden
    export let switchView
    export let orientation
    let ref

    onMount(() => {
        console.pushTarget(ref)
    })
    onDestroy(() => {
        console.removeTarget(ref)
    })

    const translate = key => EnglishLocalization.PROJECT.CONSOLE[key]


</script>
<Header
        orientation={orientation}
        hidden={hidden}
        switchView={switchView}
        title={translate("TITLE")}
        icon={"terminal"}
>
    <button
            on:click={() => {
            ref.textContent = ""
            ref.lastContent = undefined
            ref.lastLine = undefined
            ref.looped = undefined
        }}
    >
        <Icon>
            clear_all
        </Icon>
        {translate("CLEAR")}
    </button>
</Header>
<div class={"wrapper"}>
    <pre bind:this={ref} class="console"></pre>
</div>

<style>
    .wrapper {
        padding: 4px;
        width: 100%;
        height: 100%;
        overflow: hidden;
    }

    .console {
        font-size: 0.8rem;
        margin: 0;
        width: 100%;
        height: 100%;
        max-height: 100%;
        white-space: pre;
        background: var(--pj-background-tertiary);
        padding: 4px;
        color: var(--pj-color-secondary);
        border-radius: 5px;
        overflow-y: auto;
    }

</style>

// src/app/windows/project/components/console/Console.jsx
import PropTypes from "prop-types"
import React, {useEffect, useRef} from "react"
import Header from "../../../components/view/components/Header"
import styles from "./styles/Console.module.css"
import {Button, Icon} from "@f-ui/core"
import useLocalization from "../../../global/useLocalization"

export default function Console(props){
    const ref = useRef()

    useEffect(() => {
        console.pushTarget(ref.current)
        return () => console.removeTarget(ref.current)
    }, [])

    const translate = useLocalization("PROJECT", "CONSOLE")

    return (
        <>
            <Header {...props} title={translate("TITLE")} icon={"terminal"}>
                <Button
                    onClick={() => {
                        ref.current.textContent = ""
                        ref.current.lastContent = undefined
                        ref.current.lastLine = undefined
                        ref.current.looped = undefined
                    }}
                    className={styles.button}
                >
                    <Icon styles={{fontSize: "1rem"}}>
                        clear_all
                    </Icon>
                    {translate("CLEAR")}
                </Button>
            </Header>
            <div className={styles.wrapper}>
                <pre ref={ref} className={styles.console}/>
            </div>
        </>
    )
}

Console.propTypes={
    hidden: PropTypes.bool,
    switchView: PropTypes.func,
    orientation: PropTypes.string,
}
