// src/app/windows/project/components/viewport/views/SideOptions.jsx
import CameraTab from "../components/CameraTab.svelte"
import ViewportTab from "../components/ViewportTab"
import Transform from "../../component/components/Transform"
import COMPONENTS from "../../../engine/data/COMPONENTS"
import {updateTransform} from "../../component/hooks/useForm"
import VerticalTabs from "../../../../components/vertical-tab/VerticalTabs"
import React from "react"
import PropTypes from "prop-types"
import useLocalization from "../../../../global/useLocalization"

export default function SideOptions(props) {
    const {selectedEntity} = props

    const translate = useLocalization("PROJECT", "VIEWPORT")

    return (
        <VerticalTabs
            absolute={true}
            tabs={[
                {
                    label: translate("CAMERA"),
                    content: <CameraTab/>
                },
                {
                    label: translate("TITLE"),
                    content: <ViewportTab/>
                },
                {
                    label: translate("ACTIVE_ENTITY"),
                    disabled: !selectedEntity,
                    content: selectedEntity ? (
                        <Transform
                            selected={selectedEntity.components[COMPONENTS.TRANSFORM]}
                            entityID={selectedEntity.id}
                            submitRotation={(axis, data) => updateTransform(axis, data, "rotation", selectedEntity)}
                            submitScaling={(axis, data) => updateTransform(axis, data, "scaling", selectedEntity)}
                            submitTranslation={(axis, data) => updateTransform(axis, data, "translation", selectedEntity)}
                        />
                    ) : null
                }
            ]}
        />
    )
}

SideOptions.propTypes = {
    selectedEntity: PropTypes.object
}

// src/app/windows/project/views/viewport/components/SideOptions.svelte
<script>
    import CameraTab from "./settings/CameraSettings.svelte"
    import ViewportTab from "./settings/3DCursorSettings.svelte"
    // import Transform from "../../inspector/views/Transform"
    import VerticalTabs from "../../../../../components/vertical-tab/VerticalTabs.svelte";
    import RendererStoreController from "../../../stores/RendererStoreController";
    import {onDestroy} from "svelte";

    export let translate
    let settings = {}
    const unsubscribeSettings = RendererStoreController.getSettings(v => settings=v)
    onDestroy(() => unsubscribeSettings())
</script>

<VerticalTabs
        absolute={true}
        tabs={[
        {
            label: translate("CAMERA"),
            component: CameraTab,
            props: {}
        },
        {
            label: translate("TITLE"),
            component: ViewportTab,
            props: {}
        },
        /*
        {
            label: translate("ACTIVE_ENTITY"),
            disabled: !selectedEntity,
            content:  Transform,
            props: !selectedEntity ? {} : {
                selected: selectedEntity.views[COMPONENTS.TRANSFORM],
                entityID: selectedEntity.id,
                submitRotation: (axis, libs) => updateEntityTransformation(axis, libs, "rotation", selectedEntity),
                submitScaling: (axis, libs) => updateEntityTransformation(axis, libs, "scaling", selectedEntity),
                submitTranslation: (axis, libs) => updateEntityTransformation(axis, libs, "translation", selectedEntity),
            }
        }

         */
    ]}
>

</VerticalTabs>
