// src/app/windows/project/components/blueprints/components/node/Comment.jsx
import PropTypes from "prop-types"
import styles from "../../styles/Comment.module.css"
import React, {useMemo, useState} from "react"
import useComment from "../../hooks/useComment"
import KEYS from "../../../../engine/data/KEYS"

export default function Comment(props) {
    const [onEdit, setOnEdit] = useState(false)
    const [nameCache, setNameCache] = useState(props.node.name)
    const {ref, selected} = useComment(props)
    const rgb = useMemo(() => props.node.color.slice(0, 3).join(", "), [props.node])
    return (
        <g
            ref={ref}
            transform={`translate(${props.node.x} ${props.node.y})`}
        >
            <foreignObject
                onContextMenu={() => props.setSelected(props.node.id)}
                data-group={props.node.id}
                id={props.node.id}

                className={styles.wrapper}
                data-seleted={`${selected}`}
                style={{
                    background: props.node.color ? `rgba(${rgb}, .5)` : "rgba(150, 150, 150, .5)",
                    width: props.node.width + "px",
                    height: props.node.height + "px"
                }}>
                {onEdit ? <input
                    style={{background: `rgb(${rgb})`}}
                    value={nameCache}
                    onChange={v => setNameCache(v.target.value)}
                    className={styles.input}
                    onBlur={() => {
                        props.submitName(nameCache)
                        setOnEdit(false)
                    }}
                    onKeyDown={(e) => {
                        if (e.key === KEYS.Enter) {
                            props.submitName(nameCache)
                            setOnEdit(false)
                        }
                    }}
                /> : <div
                    className={styles.header}
                    style={{background: `rgb(${rgb})`}}
                    id={props.node.id + "-node"}
                    onDoubleClick={() => setOnEdit(true)}
                >
                    {props.node.name}
                </div>}
            </foreignObject>
        </g>
    )
}
Comment.propTypes = {
    submitName: PropTypes.func,
    node: PropTypes.object.isRequired,
    selected: PropTypes.array,
    setSelected: PropTypes.func,
}

// src/app/windows/project/views/shader-editor/components/node/Comment.svelte
<script>
    import KEYS from "../../../../libs/engine/data/KEYS";
    import dragNode from "../../utils/drag-node";
    import {onDestroy, onMount} from "svelte";

    export let submitName
    export let node
    export let selected
    export let setSelected
    let ref

    $: isSelected =  selected.indexOf(node.id) > -1

    const handleDragStart = (event) => {
        let isFirst, alreadyFound = false
        document.elementsFromPoint(event.clientX, event.clientY)
            .forEach(e => {
                if (e.id?.includes("-node") && !alreadyFound && e.id === (node.id + "-node"))
                    isFirst = true
                else if (e.id?.includes("-node") && !alreadyFound)
                    alreadyFound = true
            })

        if (event.button === 0 && isFirst && !isSelected)
            setSelected(node.id, event.ctrlKey)
        if (event.button === 0 && ((isSelected && event.ctrlKey) || isFirst))
            dragNode(event, ref.current, ref.current.parentNode)

    }
    onMount(() => {
        document.addEventListener("mousedown", handleDragStart)
    })
    onDestroy(() => {
        document.removeEventListener("mousedown", handleDragStart)
    })

    let onEdit = false
    let nameCache = node.name
    $: rgb = node.color.slice(0, 3).join(", ")

</script>
<g
        bind:this={ref}
        transform={`translate(${node.x} ${node.y})`}
>
    <foreignObject
            on:contextmenu={() => setSelected(node.id)}
            data-group={node.id}
            id={node.id}

            class="wrapper"
            data-seleted={`${isSelected}`}
            style={"background:" + node.color ? `rgba(${rgb}, .5)` : "rgba(150, 150, 150, .5)"}
            width="{node.width}"
            height="{node.height}">
        {#if onEdit}
            <input
                    style="background: rgb({rgb})"
                    value={nameCache}
                    on:change={v => nameCache = v.target.value}
                    class="input"
                    on:blur={() => {
                submitName(nameCache)
                onEdit = false
            }}
                    on:keydown={(e) => {
                if (e.key === KEYS.Enter) {
                    submitName(nameCache)
                    onEdit = false
                }
            }}
            />
        {:else}
            <div
                    class="header"
                    style="background: rgb({rgb})"
                    id={node.id + "-node"}
                    on:doubleclick={() => onEdit = true}
            >
                {node.name}
            </div>
        {/if}
    </foreignObject>
</g>
