// src/app/windows/project/components/files/components/Files.jsx
import PropTypes from "prop-types"
import styles from "../styles/Files.module.css"
import React, {useId, useMemo, useState} from "react"
import File from "./File"
import SelectBox from "../../../../components/select-box/SelectBox"
import handleRename from "../utils/handleRename"
import useShortcuts from "../hooks/useShortcuts"
import useContextTarget from "../../../../components/context/hooks/useContextTarget"
import getFileOptions from "../utils/getFileOptions"
import {Icon} from "@f-ui/core"
import FileSystem from "../../../libs/FileSystem"

function map(arr, items) {
    return arr.map(e => {
        return {
            ...e, children: e.isFolder ? items.filter(i => {
                return typeof i.parent === "string" && i.parent === e.id
            }).length : 0,
        }
    })
}

const TRIGGERS = [
    "data-wrapper",
    "data-file",
    "data-folder"
]
export default function Files(props) {
    const {
        fileType, setFileType,
        searchString, setSearchString,
        selected, setSelected, hook,
        translate
    } = props
    const internalID = useId()
    const [currentItem, setCurrentItem] = useState()
    const filesToRender = useMemo(() => {
        let type = fileType?.split("")
        if (type) {
            type.shift()
            type = type.join("")
        }
        if (searchString || fileType)
            return map(hook.items.filter(file => (searchString.trim() && file.name.toLowerCase().includes(searchString) || type && file.type === type && !file.isFolder), hook.items))
        if (hook.currentDirectory.id !== FileSystem.sep)
            return map(
                hook.items
                    .filter(file => file.parent === hook.currentDirectory.id),
                hook.items
            )
        return map(hook.items.filter(file => !file.parent), hook.items)
    }, [hook.items, hook.currentDirectory, searchString, fileType])
    useShortcuts(hook, selected, setSelected, internalID, translate)

    const options = useMemo(
        () => getFileOptions(hook, setCurrentItem, translate),
        [hook.items, hook.currentDirectory, hook.toCut]
    )
    useContextTarget(
        internalID,
        options,
        TRIGGERS
    )


    return (
        <div
            id={internalID}
            className={styles.content}
            data-wrapper={internalID}
        >
            <div className={styles.filesWrapper}>
                <SelectBox
                    nodes={hook.items}
                    selected={selected}
                    setSelected={setSelected}
                />
                {filesToRender.length > 0 ?
                    filesToRender.map((child, index) => (
                        <React.Fragment key={child.id}>
                            <File
                                index={index}
                                reset={() => {
                                    setSelected([])
                                    setSearchString("")
                                    setFileType(undefined)
                                }}
                                type={child.isFolder ? 0 : 1}
                                data={child}
                                childrenQuantity={child.children}
                                selected={selected}
                                setSelected={(e) => setSelected(prev => {
                                    if (e) {
                                        if (e.ctrlKey)
                                            return [...prev, child.id]
                                        return [child.id]
                                    }
                                    return []
                                })}
                                hook={hook}
                                onRename={currentItem}
                                submitRename={name => handleRename(child, name, hook, setCurrentItem)}
                            />
                        </React.Fragment>
                    ))
                    :
                    <div className={styles.empty}>
                        <Icon styles={{fontSize: "100px"}}>folder</Icon>
                        <div style={{fontSize: ".8rem"}}>
                            {translate("EMPTY")}
                        </div>
                    </div>
                }
            </div>
        </div>
    )
}

Files.propTypes = {
    translate: PropTypes.func,
    fileType: PropTypes.string,
    setFileType: PropTypes.func,
    searchString: PropTypes.string,
    setSearchString: PropTypes.func,
    visualizationType: PropTypes.number,
    selected: PropTypes.array,
    setSelected: PropTypes.func,
    hook: PropTypes.object.isRequired
}

// src/app/windows/project/views/content-browser/components/Files.svelte
<script>
    import getFileOptions from "../utils/get-file-options"
    import FileSystem from "../../../libs/FileSystem"
    import {v4} from "uuid";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import handleRename from "../utils/handle-rename";
    import File from "./File.svelte";
    import SelectBox from "../../../../../components/select-box/SelectBox.svelte";

    export let fileType
    export let setFileType
    export let searchString
    export let setSearchString
    export let selected
    export let setSelected
    export let translate
    export let items
    export let currentDirectory
    export let navigationHistory
    export let setCurrentDirectory

    function map(arr, items) {
        return arr.map(e => {
            return {
                ...e, children: e.isFolder ? items.filter(i => {
                    return typeof i.parent === "string" && i.parent === e.id
                }).length : 0,
            }
        })
    }

    const TRIGGERS = [
        "data-wrapper",
        "data-file",
        "data-folder"
    ]


    const internalID = v4()
    let currentItem
    $: filesToRender = (() => {
        let type = fileType?.split("")
        if (type) {
            type.shift()
            type = type.join("")
        }
        if (searchString || fileType)
            return map(items.filter(file => (searchString.trim() && file.name.toLowerCase().includes(searchString) || type && file.type === type && !file.isFolder), items))
        if (currentDirectory.id !== FileSystem.sep)
            return map(
                items.filter(file => file.parent === currentDirectory.id),
                items
            )
        return map(items.filter(file => !file.parent), items)
    })();
    $: options = getFileOptions(currentDirectory, setCurrentDirectory, navigationHistory, v => currentItem = v, translate)
</script>

<div
        id={internalID}
        class="content"
        data-wrapper={internalID}
>
    <div class="filesWrapper">
        <SelectBox
            nodes={items}
            selected={selected}
            setSelected={setSelected}
        />
        {#if filesToRender.length > 0}
            {#each filesToRender as child, index}
                <File
                        reset={() => {
                            setSelected([])
                            setSearchString("")
                            setFileType(undefined)
                        }}
                        type={child.isFolder ? 0 : 1}
                        data={child}
                        childrenQuantity={child.children}
                        selected={selected}
                        setCurrentDirectory={setCurrentDirectory}
                        items={items}
                        setSelected={(e) => {
                        let toSelect = []
                            if (e) {
                                if (e.ctrlKey)
                                    toSelect= [...selected, child.id]
                                    else
                                toSelect = [child.id]
                            }


                            setSelected(toSelect)
                        }}
                        onRename={currentItem}
                        submitRename={name => handleRename(child, name, currentDirectory, setCurrentDirectory, () =>currentItem = undefined )}
                />
            {/each}
            <div></div>
        {:else}
            <div class="empty">
                <Icon styles="font-size: 100px">folder</Icon>
                <div style="font-size: .8rem">
                    {translate("EMPTY")}
                </div>
            </div>
        {/if}
    </div>
</div>

<style>
    .empty {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: grid;
        align-items: center;
        align-content: center;
        justify-content: center;
        justify-items: center;
        width: 100%;
        height: 100%;
        font-weight: bold;
        color: var(--pj-color-quaternary);
    }

    .filesWrapper {
        overflow-y: auto;
        overflow-x: hidden;
        max-height: 100%;
        height: 100%;
        padding: 8px;
        gap: 8px;
        border-radius: 5px;
        background: var(--pj-background-tertiary);
        min-height: 100%;
        position: relative;
        display: grid;
        align-content: flex-start;

        --card-size: 115px;

        grid-template-columns: repeat(auto-fill, minmax(var(--card-size), 1fr));
    }

    .content {
        width: 100%;
        height: 100%;
        overflow-y: auto;
        display: flex;
        flex-flow: column;
        grid-auto-flow: row dense;
    }

</style>
