// src/Editor.svelte
<script>
    import Alert from "shared-resources/frontend/components/alert/Alert.svelte";
    import {onDestroy} from "svelte";
    import Viewport from "./views/viewport/Viewport.svelte";
    import Footer from "./components/footer/Footer.svelte";
    import EngineStore from "./stores/EngineStore";
    import ViewsContainer from "./components/view/Views.svelte";
    import SettingsStore from "./stores/SettingsStore";
    import ContextMenu from "shared-resources/frontend/components/context-menu/ContextMenu.svelte";
    import WindowOptions from "./components/frame-options/WindowOptions.svelte";

    const FALLBACK = {
        name: "Default",
        bottom: [],
        left: [],
        right: []
    }

    let view = FALLBACK
    let engine
    let settings
    const unsubscribeEngine = EngineStore.getStore(v => engine = v)
    const unsubscribeSettings = SettingsStore.getStore(v => settings = v)

    onDestroy(() => {
        unsubscribeSettings()
        unsubscribeEngine()
    })


    $: view = settings.views[settings.currentView] ? settings.views[settings.currentView] : FALLBACK
    const updateView = (key, newView) => {
        const s = {...settings}
        const copy = [...s.views]
        copy[s.currentView] = {...view, [key]: newView}
        s.views = copy
        SettingsStore.updateStore(s)
    }

</script>

<div class="wrapper">
    <Alert/>
    <WindowOptions/>
    <ContextMenu/>
    <div class="middle">
        <ViewsContainer
                id="left"
                setTabs={(tabs) => updateView("left", tabs)}
                tabs={view.left}
                reducedOpacity={engine.executingAnimation}
                leftOffset={"8px"}
                orientation={"vertical"}
                resizePosition={"left"}
        />
        <div class="content">
            <ViewsContainer
                    reducedOpacity={engine.executingAnimation}
                    id="bottom"
                    setTabs={(tabs) => updateView("top", tabs)}
                    tabs={view.top}
                    resizePosition={"bottom"}
                    orientation={"horizontal"}
            />
            <Viewport
                    viewTab={view.viewport}
                    updateView={(viewTab) => updateView("viewport", viewTab)}
            />
            <ViewsContainer
                    reducedOpacity={engine.executingAnimation}
                    id="bottom"
                    setTabs={(tabs) => updateView("bottom", tabs)}
                    tabs={view.bottom}
                    resizePosition={"top"}
                    orientation={"horizontal"}
            />
        </div>
        <ViewsContainer
                reducedOpacity={engine.executingAnimation}
                id="right"
                setTabs={(tabs) => updateView("right", tabs)}
                tabs={view.right}
                orientation={"vertical"}
                leftOffset={"0%"}
                resizePosition={"top"}
        />
    </div>
    {#if !settings.hideFooter}
        <Footer/>
    {/if}
</div>


<style>
    .wrapper {
        background: var(--pj-background-secondary);
        width: 100vw;
        height: 100vh;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        position: relative;
    }

    .content {
        width: 100%;
        height: 100%;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        user-select: none;
    }

    .middle {
        width: 100%;
        height: 100%;
        overflow: hidden;
        display: flex;

    }
</style>

// src/project/Editor.jsx
import React, {useCallback, useMemo} from "react"
import styles from "./styles/Project.module.css"
import SettingsProvider from "./providers/SettingsProvider"
import Frame from "../components/frame/Frame"
import useProjectWrapper from "./hooks/useProjectWrapper"
import PropTypes from "prop-types"
import Shortcuts from "./components/shortcuts/Shortcuts"
import ContextMenuProvider from "../components/context/hooks/ContextMenuProvider"
import useContextMenu from "../components/context/hooks/useContextMenu"
import ContextMenu from "../components/context/ContextMenu"
import {ContextWrapper} from "@f-ui/core"
import Viewport from "./components/viewport/wrapper/Viewport"
import useEditorShortcuts from "./hooks/useEditorShortcuts"
import submitPackage from "./utils/submitPackage"
import Views from "../components/view/Views"
import useOptions from "./hooks/useOptions"
import useFiles from "./hooks/useFiles"
import FilesProvider from "./providers/FilesProvider"
import EngineProvider from "./providers/EngineProvider"
import BlueprintProvider from "./providers/BlueprintProvider"
import LayoutTabs from "./components/viewport/tabs/LayoutTabs"


export default function Editor(props) {
    const {id, meta, events,  settings, load} = props
    const { serializer, engine } = useProjectWrapper(id,   settings, props.pushSettingsBlock, load)

    const contextMenuHook = useContextMenu()
    const utils = useEditorShortcuts({engine, settings, id, serializer})
    const options = useOptions(engine, serializer, settings)
    const filesHook = useFiles(engine)

    const submitMaterialPackage = useCallback((registryID, pack, matInstance) => {
        if(engine.initialized)
            submitPackage(pack, false, undefined, false, registryID, matInstance)
    }, [engine.initialized])

    const view = useMemo(() => {
        return settings.views[settings.currentView]
    }, [settings.views, settings.currentView])
    const updateView = (key, newView) => {
        const copy = [...settings.views]
        copy[settings.currentView] = {...view, [key]: newView}
        settings.views = copy
    }
    return (
        <BlueprintProvider.Provider
            value={{
                selectedEntity: engine.selectedEntity,
                materials: engine.materials,
                setMaterials: engine.setMaterials,
                submitPackage: submitMaterialPackage
            }}
        >
            <EngineProvider.Provider value={[engine, utils]}>
                <FilesProvider.Provider  value={filesHook}>
                    <ContextMenuProvider.Provider value={contextMenuHook}>
                        <SettingsProvider.Provider value={settings}>
                            <Frame
                                logoAction={true}
                                options={options}
                                hasLogo={true}
                                pageInfo={events}
                                label={meta?.name}
                            />
                            <ContextWrapper
                                attributes={{
                                    id: "context-menu-element"
                                }}
                                wrapperClassName={styles.context}
                                triggers={contextMenuHook[0].triggers}
                                className={styles.wrapper}
                                content={(selected, close) => <ContextMenu options={contextMenuHook[0].options} engine={engine} close={close} selected={selected}/>}
                            >
                                <div className={styles.middle} id={props.id + "-editor-wrapper"}>
                                    <Views
                                        setTabs={(tabs) => updateView("left", tabs)}
                                        tabs={view.left}
                                        orientation={"vertical"}
                                        leftOffset={"10px"}
                                        resizePosition={"bottom"}
                                    />
                                    <div className={styles.viewportWrapper}>
                                        <LayoutTabs/>
                                        <Viewport
                                            utils={utils}
                                            id={id}
                                            executingAnimation={engine.executingAnimation}

                                            engine={engine}
                                            allowDrop={true}
                                        />
                                    </div>

                                    <Views
                                        setTabs={(tabs) => updateView("right", tabs)}
                                        tabs={view.right}
                                        orientation={"vertical"}
                                        leftOffset={"0%"}
                                        resizePosition={"top"}
                                    />
                                </div>
                                <Views
                                    setTabs={(tabs) => updateView("bottom", tabs)}
                                    tabs={view.bottom}
                                    resizePosition={"top"}
                                    orientation={"horizontal"}
                                />
                            </ContextWrapper>
                            <Shortcuts/>
                        </SettingsProvider.Provider>
                    </ContextMenuProvider.Provider>
                </FilesProvider.Provider>
            </EngineProvider.Provider>
        </BlueprintProvider.Provider>
    )
}

Editor.propTypes={
    load: PropTypes.object,
    quickAccess: PropTypes.object,
    pushSettingsBlock: PropTypes.func,
    id: PropTypes.string,
    meta: PropTypes.object,
    events: PropTypes.object,
    settings: PropTypes.object
}
