// src/app/windows/project/components/viewport/components/CameraBar.svelte
<script>
    import {handleGrab} from "../utils/transform-camera"
    import updateCameraPlacement from "../utils/update-camera-placement"
    import {get} from "svelte/store";
    import {settingsStore} from "../../../stores/settings-store";
    import EnglishLocalization from "../../../../../static/EnglishLocalization";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import Dropdown from "../../../../../components/dropdown/Dropdown.svelte";
    import ToolTip from "../../../../../components/tooltip/ToolTip.svelte";
    import CameraGizmo from "./CameraGizmo.svelte";
    export let translate
    let cameraIsOrtho = false

    const settings = get(settingsStore)
</script>

<div class={"wrapper"} style={{right: settings.visible.sideBarViewport ? "25px" : "0"}}>
    <CameraGizmo/>
    <div class="vertical-options">
        <Dropdown hideArrow={true}>
            <button  class={"item"} slot="button">
                <Icon styles={"font-size: 1.1rem"}>videocam</Icon>
                <ToolTip>
                    Camera position
                </ToolTip>
            </button>

            <button class={"item"} on:click={() => updateCameraPlacement(0, Math.PI /2)}>
                {translate("TOP")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(0, -Math.PI /2)}>
                {translate("BOTTOM")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI, 0)}>
                {translate("LEFT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(0, 0)}>
                {translate("RIGHT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI/2, 0)}>
                {translate("FRONT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI * 1.5, 0)}>
                {translate("BACK")}
            </button>
        </Dropdown>

        <button
            class={"item"}
            on:click={() => {
                const negated = !window.renderer.camera.ortho
                window.renderer.camera.ortho = negated
                window.renderer.camera.updateProjection()
                cameraIsOrtho  = negated
            }}>
            <ToolTip>
                {translate("SWITCH_PROJECTION")}
            </ToolTip>
            {#if !cameraIsOrtho}
                <div style="width: 20px; height: 20px; perspective: 40px; transform-style: preserve-3d">
                    <Icon styles="font-size: 1.1rem; transform: rotateX(45deg)">grid_on</Icon>
                </div>
            {:else}
                <Icon styles="font-size: 1rem">grid_on</Icon>
            {/if}
        </button>

        <div class="vertical-options">
            <div class={"item dragInput"} on:mousedown={e => handleGrab(e, window.renderer.camera, 0)}>
                <ToolTip styles={{textAlign: "left", display: "grid"}}>
                    {translate("DRAG_X_ZOOM")}
                </ToolTip>
                <Icon>zoom_in</Icon>
            </div>
            <div
                class={"item dragInput"}
                on:mousedown={e => handleGrab(e, window.renderer.camera, 1)}
                on:dblclick={() => {
                    window.renderer.camera.centerOn = [0, 0, 0]
                    window.renderer.camera.updateViewMatrix()
                }}>
                <ToolTip>
                    <div>{translate("DRAG_X_DIR")}</div>
                    <div>{translate("DRAG_Y_DIR")}</div>
                    <div>{translate("DOUBLE_CLICK")}</div>
                </ToolTip>
                <Icon>back_hand</Icon>
            </div>
        </div>
    </div>
</div>

// src/project/components/viewport/side-bar/components/CameraBar.jsx
import shared from "../../options/styles/ViewportOptions.module.css"
import PropTypes from "prop-types"
import {Button, Dropdown, DropdownOption, DropdownOptions, Icon, ToolTip} from "@f-ui/core"
import React, {useMemo, useState} from "react"
import {handleGrab} from "../../wrapper/hooks/transformCamera"
import CameraGizmo from "./CameraGizmo"

export default function CameraBar(props) {
    const [cameraIsOrtho, setCameraIsOrtho] = useState(false)
    const cameraIcon = useMemo(() => {
        if (!cameraIsOrtho)
            return (
                <div
                    style={{width: "20px", height: "20px", perspective: "40px", transformStyle: "preserve-3d"}}>
                    <Icon
                        styles={{fontSize: "1.1rem", transform: "rotateX(45deg)"}}
                    >grid_on</Icon>
                </div>
            )
        else
            return <Icon styles={{fontSize: "1rem"}} >grid_on</Icon>
    }, [cameraIsOrtho])

    function bind(yaw, pitch) {
        window.renderer.camera.updateProjection()
        window.renderer.camera.yaw = yaw
        window.renderer.camera.pitch = pitch
        window.renderer.camera.updateViewMatrix()
    }
    return (
        <div className={shared.cameraWrapper} style={{right: props.sideBarOpen ? "25px" : undefined}}>
            <CameraGizmo  bind={bind} />
            <div className={shared.buttonGroup} style={{display: "grid", gap: "2px"}}>
                <Dropdown
                    hideArrow={true}
                    className={shared.groupItemVert}
                >
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        Camera position
                    </ToolTip>
                    <Icon styles={{fontSize: "1.1rem"}} >videocam</Icon>
                    <DropdownOptions>
                        <DropdownOption
                            option={{
                                label: "Top",
                                onClick: () => bind(0, Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: "Bottom",
                                onClick: () => bind(0, -Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: "Left",
                                onClick: () => bind(Math.PI , 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: "Right",
                                onClick: () => bind(0,0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: "Front",
                                onClick: () =>  bind(Math.PI /2, 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: "Back",
                                onClick: () =>  bind(Math.PI * 1.5, 0)
                            }}/>
                    </DropdownOptions>
                </Dropdown>

                <Button
                    className={shared.groupItemVert}
                    onClick={() => {
                        const negated = !window.renderer.camera.ortho
                        window.renderer.camera.ortho = negated
                        window.renderer.camera.updateProjection()
                        setCameraIsOrtho(negated)
                    }}>
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        <div>Switch between last Ortho/Perspective</div>
                    </ToolTip>
                    {cameraIcon}
                </Button>

                <div
                    className={shared.buttonGroup}
                    style={{
                        display: "grid",
                        transform: "translateY(12px)",
                        gap: "2px"
                    }}>

                    <div
                        className={[shared.groupItemVert, shared.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 0)}
                    >
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            Drag X to zoom in/out
                        </ToolTip>
                        <Icon >zoom_in</Icon>
                    </div>
                    <div
                        className={[shared.groupItemVert, shared.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 1)}
                        onDoubleClick={() => {
                            window.renderer.camera.centerOn = [0, 0, 0]
                            window.renderer.camera.updateViewMatrix()
                        }}>
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            <div>- Drag X to move forward/backwards</div>
                            <div>- Drag Y to move up/down</div>
                            <div>- Double click to center</div>
                        </ToolTip>
                        <Icon >back_hand</Icon>
                    </div>
                </div>
            </div>
        </div>
    )

}
CameraBar.propTypes = {
    sideBarOpen: PropTypes.bool
}
