// src/app/windows/project/components/viewport/components/GizmoBar.svelte
<script>
    import TRANSFORMATION_TYPE from "../../../static/misc/TRANSFORMATION_TYPE"
    import GIZMOS from "../../../static/misc/GIZMOS"
    import ToolTip from "../../../../../components/tooltip/ToolTip.svelte";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import {settingsStore} from "../../../stores/settings-store";
    import {get} from "svelte/store";
    import EnglishLocalization from "../../../../../static/EnglishLocalization";
    import ResizableBar from "../../../../../components/resizable/ResizableBar.svelte";
    import GridSizeSelector from "./GridSizeSelector.svelte";

    const DEFAULT_ROTATION = .1, ROTATION_VALUES = [1, 5, 10, 15, 30, 45, 60, 90]
    const DEFAULT_SCALE = .001, SCALE_VALUES = [.5, 1, 5, 10, 25, 50, 75, 100]
    const DEFAULT_TRANSLATION = .001, TRANSLATION_VALUES = [.5, 1, 5, 10, 25, 50, 75, 100]

    const settings = get(settingsStore)
    let minimal = false
    let ref
    let initialized = false
    export let translate
    $: {
        if (ref && !initialized && settings.extendedGizmoView !== undefined && settings.extendedGizmoView) {
            ref.style.width = "150px"
            minimal = false
            initialized = true
        }
    }

</script>

<div class={"floating"}>
    <div class={"contentWrapper"} bind:this={ref}>
        <button
            style={{borderRadius: "3px"}}
            data-minimal="{minimal}"
            class={"transformationWrapper"}
            onClick={() => {
                if (settings.transformationType !== TRANSFORMATION_TYPE.GLOBAL)
                    settings.transformationType = TRANSFORMATION_TYPE.GLOBAL
                else
                    settings.transformationType = TRANSFORMATION_TYPE.RELATIVE
            }}
        >
            <ToolTip content={`(${settings.transformationType}) Toggle transformation type`}/>
            <Icon styles={{fontSize: "1.1rem"}}>
                {settings.transformationType === TRANSFORMATION_TYPE.RELATIVE ? "place" : "language"}
            </Icon>
            {#if !minimal}
            <div class={"overflow"}>{settings.transformationType}</div>
            {/if}
        </button>
        <div class={"buttonGroup"}>
            <GridSizeSelector
                label={translate("TRANSLATION_GRID")}
                minimal={minimal}

                initialValue={DEFAULT_TRANSLATION}
                values={TRANSLATION_VALUES}
                onSave={(value) => {
                    window.renderer.gizmos.translation.gridSize = value
                }}
            >
                <Icon slot="icon" styles="font-size: 1rem">grid_4x4</Icon>
            </GridSizeSelector>
            <GridSizeSelector

                label={translate("SCALE_GRID")}
                minimal={minimal}

                initialValue={DEFAULT_SCALE}
                values={SCALE_VALUES}
                onSave={(value) => {
                    window.renderer.gizmos.scale.gridSize = value
                }}
            >
                <Icon slot="icon">linear_scale</Icon>
            </GridSizeSelector>
            <GridSizeSelector
                label={translate("ROTATION_GRID")}
                minimal={minimal}

                initialValue={DEFAULT_ROTATION}
                values={ROTATION_VALUES}
                onSave={(value) => {
                    window.renderer.gizmos.rotation.gridSize = value
                }}
            >
                <Icon slot="icon">rotate_right</Icon>
            </GridSizeSelector>
        </div>
        <div class={"buttonGroup"}>
            <button
                class={"transformationWrapper"}
                data-minimal="{minimal}"
                data-highlight={settings.gizmo === GIZMOS.NONE ? "filled" : undefined}
                on:click={() => settings.gizmo = GIZMOS.NONE}>
                <Icon>highlight_alt</Icon>
                <ToolTip content={translate("SELECTION")}/>
                {#if !minimal}
                    <div class={"overflow"}>{translate("SELECTION")}</div>
                {/if}
            </button>
            <button
                class={"transformationWrapper"}
                data-minimal="{minimal}"
                data-highlight={settings.gizmo === GIZMOS.CURSOR ? "-" : undefined}
                style="border-top: var(--pj-border-primary) 1px solid"
                on:click={() => settings.gizmo = GIZMOS.CURSOR}>
                <Icon>adjust</Icon>
                <ToolTip content={translate("CURSOR")}/>
                {#if !minimal}
                    <div class={"overflow"}>{translate("CURSOR")}</div>
                {/if}
            </button>
        </div>
        <div class={"buttonGroup"}>
            <button
                class={"transformationWrapper"}
                data-minimal="{minimal}"
                data-highlight={settings.gizmo === GIZMOS.TRANSLATION ? "-" : undefined}
                on:click={() => settings.gizmo = GIZMOS.TRANSLATION}>
                <Icon>open_with</Icon>
                {#if !minimal}
                    <div class={"overflow"}>{translate("T_GIZMO")}</div>
                {/if}
            </button>
            <button
                class={"transformationWrapper"}
                data-minimal="{minimal}"
                data-highlight={settings.gizmo === GIZMOS.ROTATION ? "-" : undefined}
                on:click={() => settings.gizmo = GIZMOS.ROTATION}>
                <Icon>360</Icon>
                {#if !minimal}
                    <div class={"overflow"}>{translate("R_GIZMO")}</div>
                {/if}
            </button>
            <button
                class={"transformationWrapper"}
                data-minimal="{minimal.toString()}"
                data-highlight={settings.gizmo === GIZMOS.SCALE ? "-" : undefined}
                on:click={() => settings.gizmo = GIZMOS.SCALE}>
                <Icon>open_in_full</Icon>
                {#if !minimal}
                    <label class={"overflow"}>{translate("S_GIZMO")}</label>
                {/if}
            </button>
        </div>
    </div>
    <ResizableBar
        type={"width"}
        onResizeEnd={() => settings.extendedGizmoView = minimal}
        onResize={() => {
            const bBox = ref.current.getBoundingClientRect()
            if (bBox.width < 80)
                minimal = true
            else
                minimal =false
        }}
    />
    <div style="max-width: 0"></div>
</div>

// src/project/components/viewport/side-bar/components/GizmoBar.jsx
import styles from "../styles/SideBar.module.css"
import {Button, Icon, ToolTip} from "@f-ui/core"
import TRANSFORMATION_TYPE from "../../../../../static/misc/TRANSFORMATION_TYPE"
import GIZMOS from "../../../../../static/misc/GIZMOS"
import React, {useContext, useEffect, useRef, useState} from "react"
import ResizableBar from "../../../../../components/resizable/ResizableBar"
import SettingsProvider from "../../../../providers/SettingsProvider"
import GridSizeSelector from "./GridSizeSelector"

const DEFAULT_ROTATION = .1, ROTATION_VALUES = [1, 5, 10, 15, 30, 45, 60, 90]
const DEFAULT_SCALE = .001, SCALE_VALUES = [.5, 1, 5, 10, 25, 50, 75, 100]
const DEFAULT_TRANSLATION = .001, TRANSLATION_VALUES = [.5, 1, 5, 10, 25, 50, 75, 100]
export default function GizmoBar() {
    const settings = useContext(SettingsProvider)


    const [minimal, setMinimal] = useState(true)
    const ref = useRef()
    const initialized = useRef(false)

    useEffect(() => {
        if (!initialized.current && settings.extendedGizmoView !== undefined && settings.extendedGizmoView) {
            ref.current.style.width = "150px"
            setMinimal(false)
            initialized.current = true
        }
    }, [settings.extendedGizmoView])

    return (
        <div className={styles.floating}>
            <div className={styles.contentWrapper} ref={ref}>
                <Button
                    styles={{borderRadius: "3px"}}
                    attributes={{"data-minimal": `${minimal}`}}
                    className={styles.transformationWrapper}
                    onClick={() => {
                        if (settings.transformationType !== TRANSFORMATION_TYPE.GLOBAL)
                            settings.transformationType = TRANSFORMATION_TYPE.GLOBAL
                        else
                            settings.transformationType = TRANSFORMATION_TYPE.RELATIVE
                    }}
                >
                    <ToolTip content={`(${settings.transformationType}) Toggle transformation type`}/>
                    <Icon styles={{fontSize: "1.1rem"}}>
                        {settings.transformationType === TRANSFORMATION_TYPE.RELATIVE ? "place" : "language"}
                    </Icon>
                    {minimal ? null : <label className={styles.overflow}>{settings.transformationType}</label>}
                </Button>
                <div className={styles.buttonGroup}>
                    <GridSizeSelector
                        label={"Translation grid"}
                        minimal={minimal}
                        icon={<Icon styles={{fontSize: "1rem"}}>grid_4x4</Icon>}
                        initialValue={DEFAULT_TRANSLATION}
                        values={TRANSLATION_VALUES}
                        onSave={(value, active) => {
                            window.renderer.gizmos.translation.gridSize = active ? value : DEFAULT_TRANSLATION
                        }}
                    />
                    <GridSizeSelector
                        label={"Scale grid"}
                        minimal={minimal}
                        icon={<Icon>linear_scale</Icon>}
                        initialValue={DEFAULT_SCALE}
                        values={SCALE_VALUES}
                        onSave={(value, active) => {
                            window.renderer.gizmos.scale.gridSize = active ? value : DEFAULT_ROTATION
                        }}
                    />
                    <GridSizeSelector
                        label={"Rotation Grid"}
                        minimal={minimal}
                        icon={<Icon>rotate_right</Icon>}
                        initialValue={DEFAULT_ROTATION}
                        values={ROTATION_VALUES}
                        onSave={(value, active) => {
                            window.renderer.gizmos.rotation.gridSize = active ? value : DEFAULT_ROTATION
                        }}
                    />
                </div>
                <div className={styles.buttonGroup}>
                    <Button
                        className={styles.transformationWrapper}
                        attributes={{"data-minimal": `${minimal}`}}
                        variant={settings.gizmo === GIZMOS.NONE ? "filled" : undefined}
                        onClick={() => settings.gizmo = GIZMOS.NONE}>
                        <Icon>highlight_alt</Icon>
                        <ToolTip content={"Select box"}/>
                        {minimal ? null : <label className={styles.overflow}>Select box</label>}
                    </Button>
                    <Button
                        className={styles.transformationWrapper}
                        attributes={{"data-minimal": `${minimal}`}}
                        variant={settings.gizmo === GIZMOS.CURSOR ? "filled" : undefined}
                        styles={{borderTop: "var(--pj-border-primary) 1px solid"}}
                        onClick={() => settings.gizmo = GIZMOS.CURSOR}>
                        <Icon>adjust</Icon>
                        <ToolTip content={"3D cursor"}/>
                        {minimal ? null : <label className={styles.overflow}>3D cursor</label>}
                    </Button>
                </div>
                <div className={styles.buttonGroup}>
                    <Button
                        className={styles.transformationWrapper}
                        attributes={{"data-minimal": `${minimal}`}}
                        variant={settings.gizmo === GIZMOS.TRANSLATION ? "filled" : undefined}
                        onClick={() => settings.gizmo = GIZMOS.TRANSLATION}>
                        <Icon>open_with</Icon>
                        {minimal ? null : <label className={styles.overflow}>Translation gizmo</label>}
                    </Button>
                    <Button
                        className={styles.transformationWrapper}
                        attributes={{"data-minimal": `${minimal}`}}
                        variant={settings.gizmo === GIZMOS.ROTATION ? "filled" : undefined}
                        onClick={() => settings.gizmo = GIZMOS.ROTATION}>
                        <Icon>360</Icon>
                        {minimal ? null : <label className={styles.overflow}>Rotation gizmo</label>}
                    </Button>
                    <Button
                        className={styles.transformationWrapper}
                        attributes={{"data-minimal": `${minimal}`}}
                        variant={settings.gizmo === GIZMOS.SCALE ? "filled" : undefined}
                        onClick={() => settings.gizmo = GIZMOS.SCALE}>
                        <Icon>open_in_full</Icon>
                        {minimal ? null : <label className={styles.overflow}>Scale gizmo</label>}
                    </Button>
                </div>
            </div>
            <ResizableBar
                type={"width"}
                onResizeEnd={() => settings.extendedGizmoView = minimal}
                onResize={() => {
                    const bBox = ref.current.getBoundingClientRect()
                    if (bBox.width < 80)
                        setMinimal(true)
                    else
                        setMinimal(false)
                }}
            />
            <div style={{maxWidth: "0px"}}/>
        </div>

    )
}
