// src/app/components/view/components/Header.jsx
import PropTypes from "prop-types"
import styles from "../styles/Views.module.css"
import {Dropdown, DropdownOption, DropdownOptions, Icon, ToolTip} from "@f-ui/core"
import React from "react"
import VIEWS from "../VIEWS"
import useLocalization from "../../../global/useLocalization"

export default function Header(props) {
    const {icon, title, children, orientation, hidden, switchView} = props
    const translate = useLocalization("COMPONENTS", "VIEWS")
    return (
        <div className={hidden ? styles.headerHidden : styles.header}>
            <Dropdown
                variant={"outlined"}
                styles={{height: orientation === "vertical" && hidden ? "fit-content" : "25px"}}
                hideArrow={true}
                className={styles.title}

            >
                <div className={styles.icon}><Icon styles={{fontSize: "1rem"}}>{icon}</Icon></div>
                <ToolTip content={props.title}/>
                <DropdownOptions>
                    <DropdownOption
                        option={{
                            label: translate("CLOSE"),
                            icon: <Icon styles={{fontSize: "1rem"}}>close</Icon>,
                            onClick: () => switchView(undefined)
                        }}
                    />
                    <div className={styles.divider}/>
                    <DropdownOption
                        option={{
                            label: translate("HIERARCHY"),
                            icon: <Icon styles={{fontSize: "1rem"}}>account_tree</Icon>,
                            onClick: () => switchView(VIEWS.HIERARCHY)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("COMP_EDITOR"),
                            icon: <Icon styles={{fontSize: "1rem"}}>category</Icon>,
                            onClick: () => switchView(VIEWS.COMPONENT)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("CONTENT_BROWSER"),
                            icon: <Icon styles={{fontSize: "1rem"}}>folder</Icon>,
                            onClick: () => switchView(VIEWS.FILES)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("SHADER_EDITOR"),
                            icon: <Icon styles={{fontSize: "1rem"}}>texture</Icon>,
                            onClick: () => switchView(VIEWS.BLUEPRINT)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("CONSOLE"),
                            icon: <Icon styles={{fontSize: "1rem"}}>terminal</Icon>,
                            onClick: () => switchView(VIEWS.CONSOLE)
                        }}
                    />
                </DropdownOptions>
            </Dropdown>
            {!hidden && children ?
                children
                :
                null}
        </div>
    )
}
Header.propTypes = {
    orientation: PropTypes.oneOf(["vertical", "horizontal"]),
    icon: PropTypes.string.isRequired,
    title: PropTypes.string,
    children: PropTypes.node,
    switchView: PropTypes.func.isRequired,
    hidden: PropTypes.bool.isRequired
}

// src/app/components/view/components/Header.svelte
<script>
    import EnglishLocalization from "../../../static/EnglishLocalization";
    import Dropdown from "../../dropdown/Dropdown.svelte";
    import ToolTip from "../../tooltip/ToolTip.svelte";
    import Icon from "../../Icon/Icon.svelte";
    import VIEWS from "../VIEWS";

    export let icon
    export let title
    export let children
    export let orientation
    export let hidden
    export let switchView
    const translate = key => EnglishLocalization.COMPONENTS.VIEWS[key]
</script>
<div
    class:headerHidden={hidden}
    class:header={!hidden}
>
    <Dropdown hideArrow={true}>
        <button
                style={"height: " +  (orientation === "vertical" && hidden ? "fit-content" : "25px")}
                class={"title"}
                slot="button"
        >
            <div class={"icon"}>
                <Icon styles="font-size: 1rem">{icon}</Icon>
            </div>
            <ToolTip content={title}/>
        </button>
        <button on:click={() => switchView(undefined)}>
            <Icon styles="font-size: 1rem">close</Icon>
            {translate("CLOSE")}
        </button>

        <div data-divider="-"></div>
        <button class="button" on:click={() => switchView(VIEWS.HIERARCHY)}>
            <Icon styles="font-size: 1rem">account_tree</Icon>
            {translate("HIERARCHY")}
        </button>
        <button class="button" on:click={() => switchView(VIEWS.COMPONENT)}>
            <Icon styles="font-size: 1rem">category</Icon>
            {translate("COMP_EDITOR")}
        </button>
        <button  class="button" on:click={() => switchView(VIEWS.FILES)}>
            <Icon styles="font-size: 1rem">folder</Icon>
            {translate("CONTENT_BROWSER")}
        </button>
        <button  class="button" on:click={() => switchView(VIEWS.BLUEPRINT)}>
            <Icon styles="font-size: 1rem">texture</Icon>
            {translate("SHADER_EDITOR")}
        </button>
        <button class="button" on:click={() => switchView(VIEWS.CONSOLE)}>
            <Icon styles="font-size: 1rem">terminal</Icon>
            {translate("CONSOLE")}
        </button>
    </Dropdown>
    {#if !hidden}
        <slot/>
    {/if}
</div>

<style>
    .button{
        height: 20px;
    }


    .title {
        background: var(--pj-background-tertiary);
        padding: 0 !important;
        display: flex;
        align-items: center;
        justify-content: center;
        color: var(--pj-color-secondary);
        min-height: 25px;
        max-height: 25px;
        min-width: 25px;
        max-width: 25px;
    }
    .header {
        display: flex;
        align-items: center;
        width: 100%;
        height: 30px;
        background-color: var(--pj-background-primary);
        padding: 2px;
        gap: 2px;

        overflow: hidden;
        max-width: 100%;
    }

    .headerHidden {
        height: 100%;
        width: 100%;
        background-color: var(--pj-background-primary);
        padding: 2px;
    }
</style>
