// src/components/view/components/Header.svelte
<script>
    import Localization from "../../../libs/libs/Localization";
    import Dropdown from "shared-resources/frontend/components/dropdown/Dropdown.svelte";
    import ToolTip from "shared-resources/frontend/components/tooltip/ToolTip.svelte";
    import Icon from "shared-resources/frontend/components/icon/Icon.svelte";
    import VIEWS from "../data/VIEWS";

    export let icon
    export let title
    export let orientation
    export let switchView
    export let currentView


    const translate = key => Localization.COMPONENTS.VIEWS[key]

</script>
<div class="header">
    <Dropdown asButton={true} styles="width: clamp(250px, 20vw, 500px);">
        <button
                style={"height: " +  (orientation === "vertical" ? "fit-content" : "25px")}
                class="title"
                slot="button"
        >
            <Icon styles="font-size: .9rem">{icon}</Icon>
            <ToolTip content={title}/>
        </button>
        <button on:click={() => switchView(undefined)}>
            <Icon styles="font-size: 1rem">close</Icon>
            <small data-overflow="-">{translate("CLOSE_VIEW")}</small>
        </button>
        <div class="content">
            <fieldset>
                <legend>{translate("MISC")}</legend>
                <div class="column">
                    <button class="button" on:click={() => switchView(VIEWS.FILES)} data-highlight={currentView === VIEWS.FILES ? "-" : ""}>
                        <Icon styles="font-size: 1rem">folder</Icon>
                        <small data-overflow="-">{translate("CONTENT_BROWSER")}</small>
                    </button>
                    <button class="button" on:click={() => switchView(VIEWS.BLUEPRINT)} data-highlight={currentView === VIEWS.BLUEPRINT ? "-" : ""}>
                        <Icon styles="font-size: 1rem">texture</Icon>
                        <small data-overflow="-">{translate("SHADER_EDITOR")}</small>
                    </button>
                </div>
            </fieldset>
            <fieldset>
                <legend>{translate("DATA")}</legend>
                <div class="column">
                    <button class="button" on:click={() => switchView(VIEWS.HIERARCHY)} data-highlight={currentView === VIEWS.HIERARCHY ? "-" : ""}>
                        <Icon styles="font-size: 1rem">account_tree</Icon>
                        <small data-overflow="-">{translate("HIERARCHY")}</small>
                    </button>
                    <button class="button" on:click={() => switchView(VIEWS.COMPONENT)} data-highlight={currentView === VIEWS.COMPONENT ? "-" : ""}>
                        <Icon styles="font-size: 1rem">category</Icon>
                        <small data-overflow="-">{translate("INSPECTOR")}</small>
                    </button>
                </div>
            </fieldset>
            <fieldset>
                <legend>{translate("SCRIPTING")}</legend>
                <div class="column">
                    <button class="button" on:click={() => switchView(VIEWS.CONSOLE)} data-highlight={currentView === VIEWS.CONSOLE ? "-" : ""}>
                        <Icon styles="font-size: 1rem">terminal</Icon>
                        <small data-overflow="-">{translate("CONSOLE")}</small>
                    </button>
                </div>
            </fieldset>
        </div>
    </Dropdown>
    <slot/>
</div>

<style>
    small {
        font-size: .7rem;
    }

    .button {
        display: flex;
        align-items: center;
        gap: 4px;
        border: none;
        height: 30px;
        background: var(--pj-background-secondary);
        white-space: nowrap;
        overflow: hidden;
    }

    .title {
        display: flex;
        align-items: center;
        gap: 2px;

        padding: 0 2px;

        border: none;
    }


    .header {
        display: flex;
        align-items: center;
        align-content: center;
        width: 100%;
        min-height: 28px;
        max-height: 28px;
        background-color: var(--pj-background-secondary);
        padding: 0 2px;
        gap: 2px;

        overflow-y: hidden;
        overflow-x: auto;
        max-width: 100%;
    }

    .content {
        display: flex;
        gap: 2px;
        width: 100%;
        overflow: hidden;
        padding-bottom: 2px;
    }

    .column {
        width: 100%;
        height: 100%;
        display: grid;
        gap: 3px;
    }

    fieldset {
        padding: 0;
        width: 100%;
    }
</style>

// src/app/components/view/components/Header.jsx
import PropTypes from "prop-types"
import styles from "../styles/Views.module.css"
import {Dropdown, DropdownOption, DropdownOptions, Icon, ToolTip} from "@f-ui/core"
import React from "react"
import VIEWS from "../VIEWS"
import useLocalization from "../../../global/useLocalization"

export default function Header(props) {
    const {icon, title, children, orientation, hidden, switchView} = props
    const translate = useLocalization("COMPONENTS", "VIEWS")
    return (
        <div className={hidden ? styles.headerHidden : styles.header}>
            <Dropdown
                variant={"outlined"}
                styles={{height: orientation === "vertical" && hidden ? "fit-content" : "25px"}}
                hideArrow={true}
                className={styles.title}

            >
                <div className={styles.icon}><Icon styles={{fontSize: "1rem"}}>{icon}</Icon></div>
                <ToolTip content={props.title}/>
                <DropdownOptions>
                    <DropdownOption
                        option={{
                            label: translate("CLOSE"),
                            icon: <Icon styles={{fontSize: "1rem"}}>close</Icon>,
                            onClick: () => switchView(undefined)
                        }}
                    />
                    <div className={styles.divider}/>
                    <DropdownOption
                        option={{
                            label: translate("HIERARCHY"),
                            icon: <Icon styles={{fontSize: "1rem"}}>account_tree</Icon>,
                            onClick: () => switchView(VIEWS.HIERARCHY)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("COMP_EDITOR"),
                            icon: <Icon styles={{fontSize: "1rem"}}>category</Icon>,
                            onClick: () => switchView(VIEWS.COMPONENT)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("CONTENT_BROWSER"),
                            icon: <Icon styles={{fontSize: "1rem"}}>folder</Icon>,
                            onClick: () => switchView(VIEWS.FILES)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("SHADER_EDITOR"),
                            icon: <Icon styles={{fontSize: "1rem"}}>texture</Icon>,
                            onClick: () => switchView(VIEWS.BLUEPRINT)
                        }}
                    />
                    <DropdownOption
                        option={{
                            label: translate("CONSOLE"),
                            icon: <Icon styles={{fontSize: "1rem"}}>terminal</Icon>,
                            onClick: () => switchView(VIEWS.CONSOLE)
                        }}
                    />
                </DropdownOptions>
            </Dropdown>
            {!hidden && children ?
                children
                :
                null}
        </div>
    )
}
Header.propTypes = {
    orientation: PropTypes.oneOf(["vertical", "horizontal"]),
    icon: PropTypes.string.isRequired,
    title: PropTypes.string,
    children: PropTypes.node,
    switchView: PropTypes.func.isRequired,
    hidden: PropTypes.bool.isRequired
}
