// src/app/windows/project/views/content-browser/components/File.svelte
<script>
    import FileSystem from "../../../libs/FileSystem"
    import handleDropFolder from "../utils/handle-drop-folder"
    import Input from "../../../../../components/input/Input.svelte";
    import FILE_TYPES from "../../../../../../static/FILE_TYPES";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import Preview from "../../../../../components/preview/Preview.svelte";
    import getFileIcon from "../utils/get-file-icon";
    import FileStoreController from "../../../stores/FileStoreController";

    const {shell} = window.require("electron")

    export let childrenQuantity
    export let reset
    export let type
    export let data
    export let selected
    export let setSelected
    export let hook
    export let onRename
    export let submitRename
    export let items
    export let setCurrentDirectory
    let currentLabel
    $: {
        currentLabel = data.name
    }
    $: isSelected = selected.includes(data.id)
    $: metadata = {
        path: window.fileSystem.path + FileSystem.sep + "previews" + FileSystem.sep + data.registryID + FILE_TYPES.PREVIEW,
        type: data.type ? "." + data.type : "folder",
        childrenQuantity,
        icon: getFileIcon(data.type)
    }
</script>
<div
        on:dragover={(e) => {
        if (type === 0) {
            e.preventDefault()
          //  e.currentTarget.classList.addhovered)
        }
    }}
        on:dragleave={(e) => {
        e.preventDefault()
        //e.currentTarget.classList.removehovered)
    }}
        on:drop={e => {
        e.preventDefault()
        //e.currentTarget.parentNode.classList.removehovered)
        handleDropFolder(e.dataTransfer.getData("text"), data.id, hook)
    }}
        onContextMenu={() => setSelected(data.id)}
        data-file={type === 0 ? undefined : data.id}
        data-folder={type !== 0 ? undefined : data.id}
        on:dblclick={() => {
        if (type === 1) {
            if (data.type === FILE_TYPES.SCRIPT.replace(".", ""))
                shell.openPath(FileStoreController.ASSETS_PATH + FileSystem.sep + data.id).catch()
            else
                setSelected(data.id)
        } else {
            reset()
            setCurrentDirectory(data)
        }
    }}
        id={data.id}
        on:dragstart={(event) => {
        if (event.ctrlKey) {
            const selected = selected.map(s => {
                return items.find(i => i.id === s)
            }).filter(e => e && !e.isFolder && e.type === "mesh")
            event.dataTransfer.setData("text", JSON.stringify(selected.map(s => s.registryID)))
        } else
            event.dataTransfer.setData("text", JSON.stringify([type === 1 ? data.registryID : data.id]))
    }}
        draggable="{onRename !== data.id}"
        on:click={setSelected}
        style={isSelected ? "background: var(--pj-accent-color-light);" : "" +  (FileStoreController.toCut.includes(data.id) ? "opacity: .5;" : "")}
        class="file"
>

    {#if metadata.type === FILE_TYPES.SCRIPT}
        <div class="icon">
            <Icon styles="font-size: 3.5rem; ">javascript</Icon>
        </div>
    {:else if metadata.type === FILE_TYPES.SCENE}
        <div class="icon">
            <Icon styles="font-size: 3.5rem; ">inventory_2</Icon>
        </div>
    {:else if metadata.type === "folder"}
        <div class="icon">
            <Icon styles="font-size: 3.5rem; color: var(--folder-color)">folder</Icon>
            <div
                title={"Files"}
                class="floatingIconWrapper"
            >
                {childrenQuantity}
            </div>
        </div>
    {:else}
        <div class="icon" >
            <Preview path={metadata.path}>
                <img class="image" slot="image" alt="logo" let:src src={src}>
                <Icon slot="icon" styles="font-size: 4rem">
                    {metadata.icon}
                </Icon>

                <div class= "floatingIconWrapper">
                    <Icon class="floatingIcon">{metadata.icon}</Icon>
                </div>
            </Preview>
        </div>
    {/if}
    {#if onRename === data.id} ?
        <Input
                onEnter={() => submitRename(currentLabel)}
                onBlur={() => submitRename(currentLabel)}
                setSearchString={e => currentLabel = e.target.value}
                searchString={currentLabel}
        />
    {:else }
        <div data-overflow="-" class="label">
            {currentLabel}
        </div>
    {/if}
</div>

<style>
    .icon {
        position: relative;
        color: var(--pj-color-secondary);
        display: flex;
        justify-content: center;
        align-items: center;
        align-content: center;
        width: 100%;
        height: 100%;
        overflow: hidden;
        border-radius: 5px;
    }


    .floatingIconWrapper {
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--pj-background-tertiary);
        position: absolute;
        bottom: 4px;
        right: 4px;
        width: 1.3rem;
        height: 1.3rem;
        border-radius: 3px;
        font-size: 0.7rem !important;
    }

    .floatingIcon {
        color: var(--pj-color-secondary);
        font-size: 1.1rem !important;
    }

    .image {
        max-height: 100%;
    }

    .label {
        font-size: 0.75rem;
        padding: 4px 4px 8px;
        text-align: center;
        line-height: 100%;
        min-height: 20px;
    }


    .file {
        position: relative;
        overflow: hidden;
        border-radius: 5px;
        color: var(--pj-color-secondary);
        gap: 4px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 115px;
        width: 115px;
        outline: transparent 2px solid;
        cursor: pointer;
        flex: 1 1 80px;
        padding: 4px 4px 0;
    }

    .file:hover,
    .file:active {
        border-color: transparent;
        background: var(--pj-background-primary);
    }



</style>

// src/app/windows/project/components/files/components/File.jsx
import PropTypes from "prop-types"
import styles from "../styles/File.module.css"
import React, {useEffect, useMemo, useState} from "react"
import getFileIcon from "../utils/getFileIcon"
import FILE_TYPES from "../../../../../public/static/FILE_TYPES"
import FileSystem from "../../../libs/FileSystem"
import handleDropFolder from "../utils/handleDropFolder"

const {shell} = window.require("electron")
export default function File(props) {
    const [currentLabel, setCurrentLabel] = useState(props.data.name)
    useEffect(() => setCurrentLabel(props.data.name), [props.data.name])
    const selected = useMemo(() => props.selected.includes(props.data.id), [props.selected])
    const icon = useMemo(() => {
        return getFileIcon({
            path: window.fileSystem.path + FileSystem.sep + "previews" +FileSystem.sep +  props.data.registryID + FILE_TYPES.PREVIEW,
            type: props.data.type ? "." + props.data.type : "folder",
            childrenQuantity: props.childrenQuantity
        })
    }, [props.data])

    return (
        <div
            onDragOver={(e) => {
                if (props.type === 0) {
                    e.preventDefault()
                    e.currentTarget.classList.add(styles.hovered)
                }
            }}
            onDragLeave={(e) => {
                e.preventDefault()
                e.currentTarget.classList.remove(styles.hovered)
            }}
            onDrop={e => {
                e.preventDefault()
                e.currentTarget.parentNode.classList.remove(styles.hovered)
                handleDropFolder(e.dataTransfer.getData("text"), props.data.id, props.hook)
            }}
            onContextMenu={() => props.setSelected(props.data.id)}
            data-file={props.type === 0 ? undefined : props.data.id}
            data-folder={props.type !== 0 ? undefined : props.data.id}
            onDoubleClick={() => {
                if (props.type === 1) {
                    if (props.data.type === FILE_TYPES.SCRIPT.replace(".", ""))
                        shell.openPath(props.hook.path + FileSystem.sep + props.data.id).catch()
                    else
                        props.setSelected(props.data.id)
                } else {
                    props.reset()
                    props.hook.setCurrentDirectory(props.data)
                }
            }}
            id={props.data.id}
            onDragStart={(event) => {
                if (event.ctrlKey) {
                    const selected = props.selected.map(s => {
                        return props.hook.items.find(i => i.id === s)
                    }).filter(e => e && !e.isFolder && e.type === "mesh")
                    event.dataTransfer.setData("text", JSON.stringify(selected.map(s => s.registryID)))
                } else
                    event.dataTransfer.setData("text", JSON.stringify([props.type === 1 ? props.data.registryID : props.data.id]))
            }}
            draggable={props.onRename !== props.data.id}
            onClick={props.setSelected}
            style={{background: selected ? "var(--pj-accent-color-light)" : undefined, opacity: props.hook.toCut.includes(props.data.id) ? ".5" : undefined}}
            className={styles.file}
        >

            {icon}
            {props.onRename === props.data.id ?
                <input
                    className={styles.input}
                    onKeyPress={key => {
                        if (key.code === "Enter")
                            props.submitRename(currentLabel)
                    }}
                    onBlur={() => {
                        props.submitRename(currentLabel)
                    }}
                    onChange={e => setCurrentLabel(e.target.value)}
                    value={currentLabel}
                />
                :
                <div className={[styles.label, styles.overflow].join(" ")}>
                    {currentLabel}
                </div>
            }
        </div>
    )
}

File.propTypes = {
    index: PropTypes.number,
    childrenQuantity: PropTypes.number,
    reset: PropTypes.func,
    type: PropTypes.oneOf([0, 1]),
    data: PropTypes.object,
    selected: PropTypes.array,
    setSelected: PropTypes.func,
    hook: PropTypes.object,
    onRename: PropTypes.string,
    submitRename: PropTypes.func
}
