// src/frontend/project/views/content-browser/components/SideBar.svelte
<script>
    import FilesAPI from "../../../../libs/files/FilesAPI"
    import Icon from "../../../../components/icon/Icon.svelte";
    import Accordion from "../../../../components/accordion/Accordion.svelte";

    export let translate = undefined
    export let bookmarks = undefined
    export let setCurrentDirectory = undefined
    export let items = undefined
    export let currentDirectory = undefined

    $: assets = items.filter(item => item.isFolder && !item.parent)

</script>
<div class="wrapper">
    <Accordion>
        <div class="summary" slot="header">
            <Icon>
                inventory_2
            </Icon>
            {translate("ASSETS")}
        </div>
        <div
                data-highlight={currentDirectory.id === FilesAPI.sep ? "-" : undefined}
                class="folder"
                on:click={() => setCurrentDirectory({id: FilesAPI.sep})}
        >
            <Icon styles={{fontSize: "1.1rem"}}>arrow_upward</Icon>
            ...
        </div>
        {#each assets as b, i}
            <div
                    data-highlight={b.id === currentDirectory.id ? "-" : undefined}
                    class="folder"
                    on:click={() => setCurrentDirectory(b)}
            >
                <Icon styles="color: var(--folder-color)">
                    folder
                </Icon>
                {b.name}
            </div>
        {/each}

    </Accordion>

    <Accordion>
        <div class="summary" slot="header">
            <Icon>
                book
            </Icon>
            {translate("BOOKMARKS")}
        </div>

        {#each bookmarks as b, i}
            <div
                    class="folder"
                    on:click={() => setCurrentDirectory({id: b.path})}
            >

                <Icon styles="color: var(--folder-color)">
                    folder
                </Icon>
                {b.name}
            </div>
        {/each}
    </Accordion>
</div>

<style>
    .wrapper{
        display: grid;
        align-content: flex-start;
        gap: 2px;
        overflow-y: auto;
        width: 300px;
        padding: 0 4px;
        background: var(--pj-background-secondary);
    }


    .summary {
        font-size: 0.7rem;
        gap: 4px;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: flex-start;
    }

    .folder {
        height: 20px;
        font-size: 0.7rem;
        display: flex;
        align-items: center;
        justify-content: flex-start;
        gap: 4px;
        cursor: pointer;
    }
</style>

// src/app/windows/project/components/files/components/SideBar.jsx
import PropTypes from "prop-types"
import React, {useId, useMemo} from "react"
import styles from "../styles/SideBar.module.css"
import {Icon} from "@f-ui/core"
import handleDropFolder from "../utils/handleDropFolder"
import FileSystem from "../../../libs/FileSystem"

export default function SideBar(props) {
    const {translate, hook} =props
    const assets = useMemo(
        () => hook.items.filter(item => item.isFolder && !item.parent),
        [hook.items]
    )

    // const [ref, offset, maxDepth] = useInfiniteScroll()
    const internalID = useId()

    return (
        <div className={styles.wrapper}>
            <div className={styles.section}>
                <details className={styles.tree} open={true}>
                    <summary className={styles.summary}>
                        <Icon className={styles.iconDropdown}>arrow_drop_down</Icon>
                        <Icon styles={{fontSize: "1rem"}}>
							inventory_2
                        </Icon>
                        {translate("ASSETS")}
                    </summary>
                    <div className={styles.content}>
                        <div
                            data-highlight={hook.currentDirectory.id === FileSystem.sep}
                            className={styles.folder}
                            onDragOver={e => {
                                e.preventDefault()
                                e.target.classList.add(styles.hovered)
                            }}
                            onDragLeave={e => {
                                e.preventDefault()
                                e.target.classList.remove(styles.hovered)
                            }}
                            onDrop={e => {
                                e.preventDefault()
                                e.target.classList.remove(styles.hovered)
                                handleDropFolder(e.dataTransfer.getData("text"), FileSystem.sep, hook)
                            }}
                            onClick={() => hook.setCurrentDirectory({id: FileSystem.sep})}
                        >
                            <Icon styles={{fontSize: "1.1rem"}}>arrow_upward</Icon>
							...
                        </div>
                        {assets.map((b, i) => (
                            <div
                                data-highlight={b.id === hook.currentDirectory.id}
                                className={styles.folder}
                                key={i + "-asset-" + internalID}

                                onDragOver={e => {
                                    e.preventDefault()
                                    e.target.classList.add(styles.hovered)
                                }}
                                onDragLeave={e => {
                                    e.preventDefault()
                                    e.target.classList.remove(styles.hovered)
                                }}
                                onDrop={e => {
                                    e.preventDefault()
                                    e.target.classList.remove(styles.hovered)
                                    handleDropFolder(e.dataTransfer.getData("text"), b.id, hook)
                                }}
                                onClick={() => hook.setCurrentDirectory(b)}
                            >
                                <Icon styles={{fontSize: "1.1rem", color: "var(--folder-color)"}}>
									folder
                                </Icon>
                                {b.name}
                            </div>
                        ))}
                    </div>
                </details>
            </div>
            <div className={styles.section}>
                <details className={styles.tree}>
                    <summary className={styles.summary}>
                        <Icon className={styles.iconDropdown}>arrow_drop_down</Icon>
                        <Icon styles={{fontSize: "1rem"}}>
							book
                        </Icon>
                        {translate("BOOKMARKS")}
                    </summary>
                    <div className={styles.content}>
                        {hook.bookmarks.map((b, i) => (
                            <div
                                className={styles.folder}
                                key={i + "-bookmark-" + internalID}
                                onDragOver={e => {
                                    e.preventDefault()
                                    e.target.classList.add(styles.hovered)
                                }}
                                onDragLeave={e => {
                                    e.preventDefault()
                                    e.target.classList.remove(styles.hovered)
                                }}
                                onDrop={e => {
                                    e.preventDefault()
                                    e.target.classList.remove(styles.hovered)
                                    handleDropFolder(e.dataTransfer.getData("text"), b.id, hook)
                                }}
                                onClick={() => hook.setCurrentDirectory({...b, id: b.path})}
                            >

                                <Icon styles={{fontSize: "1.1rem", color: "var(--folder-color)"}}>
									folder
                                </Icon>
                                {b.name}
                            </div>
                        ))}
                    </div>
                </details>
            </div>
        </div>
    )
}

SideBar.propTypes = {
    translate: PropTypes.func.isRequired,
    hook: PropTypes.object.isRequired
}
