// src/app/windows/project/components/viewport/components/Add.svelte
<script>
    import EnglishLocalization from "../../../../../static/EnglishLocalization";
    import {get} from "svelte/store";
    import {engine as engineStore} from "../../../stores/engine-store";
    import Entity from "../../../libs/engine/basic/Entity";
    import COMPONENTS from "../../../libs/engine/data/COMPONENTS";
    import ProbeComponent from "../../../libs/engine/components/ProbeComponent";
    import TransformComponent from "../../../libs/engine/components/TransformComponent";
    import {ENTITY_ACTIONS} from "../../../libs/engine-extension/entityReducer";
    import Dropdown from "../../../../../components/dropdown/Dropdown.svelte";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import CameraComponent from "../../../libs/engine/components/CameraComponent";
    import PointLightComponent from "../../../libs/engine/components/PointLightComponent";
    import DirectionalLightComponent from "../../../libs/engine/components/DirectionalLightComponent";

    const engine = get(engineStore)
    const createCM = (asDiffuse) => {
        const actor = new Entity(undefined, asDiffuse ? "Diffuse probe" : "Specular probe")
        actor.components[COMPONENTS.PROBE] = new ProbeComponent()
        actor.components[COMPONENTS.PROBE].specularProbe = !asDiffuse
        actor.components[COMPONENTS.TRANSFORM] = new TransformComponent()
        actor.components[COMPONENTS.TRANSFORM].translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
        actor.components[COMPONENTS.TRANSFORM].lockedRotation = true
        actor.components[COMPONENTS.TRANSFORM].lockedScaling = true

        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
    }
    const translate = (key) => EnglishLocalization.PROJECT.VIEWPORT[key]
</script>

<Dropdown>
    <button slot="button">
        {translate("ADD")}
    </button>
    <div>
        <div class={"dividerWrapper"}>
            {translate("LIGHTS")}
            <div class={"divider"}></div>
        </div>
        <button
            on:click={() =>  {
                const actor = new Entity(undefined, translate("POINT_LIGHT"))
                actor.components[COMPONENTS.POINT_LIGHT] = new PointLightComponent()
                const transformComponent = new TransformComponent()
                transformComponent.translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
                transformComponent.lockedRotation = true
                transformComponent.lockedScaling = true
                actor.components[COMPONENTS.TRANSFORM] = transformComponent
                engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
            }}
        >
            <Icon styles={"font-size: 1.1rem"}>lightbulb</Icon>
            {translate("POINT_LIGHT")}
        </button>

        <button
            on:click={() => {
                const actor = new Entity(undefined, translate("DIRECTIONAL_LIGHT"))

                const transformComponent = new TransformComponent()
                transformComponent.translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
                transformComponent.lockedRotation = true
                transformComponent.lockedScaling = true
                actor.components[COMPONENTS.TRANSFORM] = transformComponent
                actor.components[COMPONENTS.DIRECTIONAL_LIGHT] = new DirectionalLightComponent(undefined, actor)

                engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
            }}
        >
            <Icon styles={"font-size: 1.1rem"}>light_mode</Icon>
            {translate("DIRECTIONAL_LIGHT")}
        </button>

        <div class={"dividerWrapper"}>
            {translate("AMBIENT")}
            <div class={"divider"}></div>
        </div>


        <button on:click={() => createCM()}>
            <Icon styles={"font-size: 1.1rem"}>lens_blur</Icon>
            {translate("SPECULAR_PROBE")}
        </button>
        <button on:click={() => createCM(true)}>
            <Icon styles={"font-size: 1.1rem"}>lens_blur</Icon>
            {translate("DIFFUSE_PROBE")}
        </button>
        <div class={"dividerWrapper"}>
            {translate("UTILS")}
            <div class={"divider"}></div>
        </div>
        <button
            on:click={() => {
                const actor = new Entity(undefined, translate("CAMERA"))
                actor.components[COMPONENTS.CAMERA] = new CameraComponent()

                actor.components[COMPONENTS.TRANSFORM] = new TransformComponent()
                actor.components[COMPONENTS.TRANSFORM].translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
                actor.components[COMPONENTS.TRANSFORM].rotation = [0, 0, 0]
                actor.components[COMPONENTS.TRANSFORM].scaling = [0.8578777313232422, 0.5202516317367554, 0.2847398519515991]
                actor.components[COMPONENTS.TRANSFORM].lockedScaling = true


                engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
            }}
        >
            <Icon styles={"font-size: 1.1rem"}>videocam</Icon>
            {translate("CAMERA")}
        </button>
    </div>
</Dropdown>

<style>
    .dividerWrapper {

    }

    .divider {

    }
</style>

// src/project/components/viewport/options/components/Add.jsx
import styles from "../styles/ViewportOptions.module.css"
import {Dropdown, DropdownOption, DropdownOptions, Icon} from "@f-ui/core"
import Entity from "../../../../engine/basic/Entity"
import COMPONENTS from "../../../../engine/templates/COMPONENTS"
import PointLightComponent from "../../../../engine/components/PointLightComponent"
import TransformComponent from "../../../../engine/components/TransformComponent"
import React, {useContext} from "react"
import DirectionalLightComponent from "../../../../engine/components/DirectionalLightComponent"
import CameraComponent from "../../../../engine/components/CameraComponent"
import ProbeComponent from "../../../../engine/components/ProbeComponent"
import LineComponent from "../../../../engine/components/LineComponent"
import {ENTITY_ACTIONS} from "../../../../engine-extension/entityReducer"
import EngineProvider from "../../../../providers/EngineProvider"

export default function Add() {
    const [engine] = useContext(EngineProvider)
    const createCM = (asDiffuse) => {
        const actor = new Entity(undefined, asDiffuse ? "Diffuse probe" : "Specular probe")
        actor.components[COMPONENTS.PROBE] = new ProbeComponent()
        actor.components[COMPONENTS.PROBE].specularProbe = !asDiffuse
        actor.components[COMPONENTS.TRANSFORM] = new TransformComponent()
        actor.components[COMPONENTS.TRANSFORM].translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
        actor.components[COMPONENTS.TRANSFORM].lockedRotation = true
        actor.components[COMPONENTS.TRANSFORM].lockedScaling = true

        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
    }
    return (
        <Dropdown className={styles.dropdown}>
            Add
            <DropdownOptions>
                <div className={styles.dividerWrapper}>
                    Lights
                    <div className={styles.divider}/>
                </div>
                <DropdownOption option={{
                    label: "Point light",
                    icon: <Icon
                        styles={{fontSize: "1.2rem"}}>lightbulb</Icon>,
                    onClick: () => {
                        const actor = new Entity(undefined, "Point light")
                        actor.components[COMPONENTS.POINT_LIGHT] = new PointLightComponent()
                        actor.components[COMPONENTS.TRANSFORM] = new TransformComponent()
                        actor.components[COMPONENTS.TRANSFORM].translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
                        actor.components[COMPONENTS.TRANSFORM].lockedRotation = true
                        actor.components[COMPONENTS.TRANSFORM].lockedScaling = true

                        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
                    }
                }}/>
                <DropdownOption option={{
                    disabled: true,
                    label: "Spot light",
                    icon: <Icon
                        styles={{fontSize: "1.2rem"}}>flashlight_on</Icon>,
                    onClick: () => {
                        const actor = new Entity(undefined, "Point light")
                        actor.components[COMPONENTS.DIRECTIONAL_LIGHT] = new PointLightComponent()
                        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
                    }
                }}/>
                <DropdownOption option={{

                    label: "Directional light",
                    icon: <Icon
                        styles={{fontSize: "1.1rem"}}>light_mode</Icon>,
                    onClick: () => {

                        const actor = new Entity(undefined, "Directional light")
                        actor.components[COMPONENTS.DIRECTIONAL_LIGHT] = new DirectionalLightComponent()
                        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
                    }
                }}/>
                <div className={styles.dividerWrapper}>
                    Ambient
                    <div className={styles.divider}/>
                </div>
                <DropdownOption option={{
                    label: "Specular probe",
                    icon: <Icon
                        styles={{fontSize: "1.1rem"}}>lens_blur</Icon>,
                    onClick: () => createCM()
                }}/>
                <DropdownOption option={{
                    label: "Diffuse probe",
                    icon: <Icon
                        styles={{fontSize: "1.1rem"}}>lens_blur</Icon>,
                    onClick: () =>  createCM(true)
                }}/>

                <div className={styles.dividerWrapper}>
                    Utils
                    <div className={styles.divider}/>
                </div>
                <DropdownOption option={{
                    label: "Camera",
                    icon: <Icon
                        styles={{fontSize: "1.1rem"}}>videocam</Icon>,
                    onClick: () => {
                        const actor = new Entity(undefined, "Camera")
                        actor.components[COMPONENTS.CAMERA] = new CameraComponent()

                        actor.components[COMPONENTS.TRANSFORM] = new TransformComponent()
                        actor.components[COMPONENTS.TRANSFORM].translation = window.renderer.cursor.components[COMPONENTS.TRANSFORM].translation
                        actor.components[COMPONENTS.TRANSFORM].rotation = [0, 0, 0]
                        actor.components[COMPONENTS.TRANSFORM].scaling = [0.8578777313232422, 0.5202516317367554, 0.2847398519515991]
                        actor.components[COMPONENTS.TRANSFORM].lockedScaling = true


                        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
                    }
                }}/>
                <DropdownOption option={{
                    label: "Line",
                    icon: <Icon
                        styles={{fontSize: "1.1rem"}}>arrow_right_alt</Icon>,
                    onClick: () => {
                        const actor = new Entity(undefined, "Line")
                        actor.components[COMPONENTS.LINE] = new LineComponent()

                        engine.dispatchEntities({type: ENTITY_ACTIONS.ADD, payload: actor})
                    }
                }}/>
            </DropdownOptions>
        </Dropdown>
    )
}
