// src/project/components/viewport/Viewport.jsx
import PropTypes from "prop-types"
import styles from "./styles/Viewport.module.css"
import React, {useContext, useEffect, useId, useMemo} from "react"
import useContextTarget from "../../../components/context/hooks/useContextTarget"
import RENDER_TARGET from "../../static/misc/RENDER_TARGET"
import HeaderOptions from "./views/HeaderOptions"
import COMPONENTS from "../../engine/data/COMPONENTS"
import SelectBox from "../../../components/select-box/SelectBox"
import Conversion from "../../engine/utils/Conversion"
import GIZMOS from "../../static/misc/GIZMOS"
import SettingsProvider from "../../context/SettingsProvider"
import importData from "../../libs/importer/import"
import getOptionsViewport from "./utils/getOptionsViewport"
import windowBuilder from "../../engine/windowBuilder"
import EditorEngine from "../../engine-extension/EditorEngine"
import SideOptions from "./views/SideOptions"
import updateCursor from "./utils/updateCursor"
import onViewportClick from "./utils/onViewportClick"
import drawIconsToDepth from "./utils/drawIconsToDepth"

const TRIGGERS = ["data-viewport"]
const LEFT_BUTTON = 0
const WORKER = new Worker(new URL("./utils/findEntities.js", import.meta.url))
export default function Viewport(props) {
    const renderer = window.renderer
    const settings = useContext(SettingsProvider)
    const internalID = useId()
    const optionsViewport = useMemo(
        () => getOptionsViewport(props.engine, props.utils),
        [props.engine.selected, props.utils]
    )
    useEffect(() => {
        windowBuilder(document.getElementById(RENDER_TARGET), settings.resolution, EditorEngine)
        props.engine.setViewportInitialized(true)
    }, [])

    let latestTranslation

    function handleMouse(e) {
        if (e.type === "mousemove") {
            latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera).slice(0, 3)
            updateCursor(latestTranslation)
        } else
            document.removeEventListener("mousemove", handleMouse)
    }

    useContextTarget(internalID, optionsViewport, TRIGGERS)

    return (
        <>
            {props.engine.executingAnimation ? null : <HeaderOptions/>}
            <div
                onMouseDown={e => {
                    e.currentTarget.started = performance.now()
                    e.currentTarget.startedCoords = {x: e.clientX, y: e.clientY}
                    if (e.button === LEFT_BUTTON && settings.gizmo === GIZMOS.CURSOR && e.target === window.gpu.canvas || e.target === e.currentTarget) {
                        latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera, renderer.cursor.components[COMPONENTS.TRANSFORM].translation).slice(0, 3)
                        updateCursor(latestTranslation)
                        document.addEventListener("mousemove", handleMouse)
                        document.addEventListener("mouseup", handleMouse, {once: true})
                    }
                }}
                onClick={event => onViewportClick(event, settings, props.engine.setSelected)}
                onDragOver={e => {
                    e.preventDefault()
                    e.currentTarget.classList.add(styles.hovered)
                }}
                onDragLeave={e => {
                    e.preventDefault()
                    e.currentTarget.classList.remove(styles.hovered)
                }}
                onDrop={e => {
                    // TODO - APPLY MATERIAL BY DROPPING IT ON MESH (PICK MESH AND LOAD MATERIAL)
                    e.preventDefault()
                    e.currentTarget.classList.remove(styles.hovered)
                    importData(e, props.engine)
                }}

                data-viewport={RENDER_TARGET}
                id={internalID}
                className={styles.viewport}
            >
                <canvas
                    id={RENDER_TARGET}
                    style={{width: "100%", height: "100%", background: "transparent"}}
                    width={settings.resolution[0]}
                    height={settings.resolution[1]}
                />
                <SideOptions
                    selectedEntity={props.engine.selectedEntity}
                    executingAnimation={props.engine.executingAnimation}
                />
                <SelectBox
                    targetElementID={RENDER_TARGET}
                    disabled={settings.gizmo === GIZMOS.CURSOR}
                    setSelected={(_, startCoords, endCoords) => {
                        if (startCoords && endCoords) {
                            drawIconsToDepth()
                            const depthFBO = renderer.renderingPass.depthPrePass.frameBuffer
                            const size = {
                                w: depthFBO.width,
                                h: depthFBO.height
                            }
                            const nStart = Conversion.toQuadCoord(startCoords, size)
                            const nEnd = Conversion.toQuadCoord(endCoords, size)

                            try {
                                const data = renderer.picking.readBlock(depthFBO, nStart, nEnd)
                                WORKER.postMessage({entities: renderer.entities, data})
                                WORKER.onmessage = ({data: selected}) => props.engine.setSelected(selected)
                            } catch (err) {
                                console.error(err, startCoords, nStart)
                            }
                        }
                    }}
                    target={RENDER_TARGET}
                    selected={[]}
                    nodes={[]}
                />
            </div>
        </>
    )
}

Viewport.propTypes = {
    utils: PropTypes.object,
    executingAnimation: PropTypes.bool,
    engine: PropTypes.object,
    id: PropTypes.string
}

// src/app/windows/project/views/viewport/Viewport.svelte
<script>
    import GIZMOS from "../../static/misc/GIZMOS"
    import importData from "../../libs/importer/import"
    import updateCursor from "./utils/update-cursor"
    import onViewportClick from "./utils/on-viewport-click"
    import Conversion from "../../libs/engine/utils/Conversion";
    import entitySearchWorker from "../../../../web-workers/entity-search-worker";
    import ViewportSettings from "./views/ViewportSettings.svelte";
    import CameraBar from "./components/CameraBar.svelte";
    import INFORMATION_CONTAINER from "../../static/misc/INFORMATION_CONTAINER";
    import EnglishLocalization from "../../../../libs/EnglishLocalization";
    import GizmoBar from "./components/GizmoBar.svelte";
    import SideOptions from "./views/SideOptions.svelte";
    import COMPONENTS from "../../libs/engine/data/COMPONENTS";
    import DataStoreController from "../../stores/DataStoreController";
    import {onDestroy} from "svelte";
    import SelectBox from "../../../../components/select-box/SelectBox.svelte";
    import RENDER_TARGET from "../../static/misc/RENDER_TARGET";
    import drawIconsToBuffer from "./utils/draw-icons-to-buffer";

    export let isReady = false

    const LEFT_BUTTON = 0
    let WORKER = entitySearchWorker()
    let gizmoSystem
    let hovered = false
    let latestTranslation

    let engine = {}
    let settings = {}
    const unsubscribeEngine = DataStoreController.getEngine(v => engine = v)
    const unsubscribeSettings = DataStoreController.getSettings(v => settings = v)
    onDestroy(() => {
        unsubscribeEngine()
        unsubscribeSettings()
    })

    const id = sessionStorage.getItem("electronWindowID")

    function handleMouse(e) {
        if (e.type === "mousemove") {
            latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera).slice(0, 3)
            updateCursor(latestTranslation)
        } else
            document.removeEventListener("mousemove", handleMouse)
    }

    function gizmoMouseMove(event) {
        if (gizmoSystem && gizmoSystem.targetGizmo)
            gizmoSystem.targetGizmo.onMouseMove(event)
    }

    function onMouseDown(e) {
        if (!window.renderer)
            return
        e.currentTarget.startedCoords = {x: e.clientX, y: e.clientY}
        if (e.button === LEFT_BUTTON && settings.gizmo === GIZMOS.CURSOR && e.target === window.gpu.canvas || e.target === e.currentTarget) {
            latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera, renderer.cursor.components[COMPONENTS.TRANSFORM].translation).slice(0, 3)
            updateCursor(latestTranslation)
            document.addEventListener("mousemove", handleMouse)
            document.addEventListener("mouseup", handleMouse, {once: true})
        }
        if (e.button === LEFT_BUTTON && settings.gizmo !== GIZMOS.CURSOR) {
            gizmoSystem = window.renderer.editorSystem.gizmoSystem
            if (gizmoSystem.targetGizmo) {
                gizmoSystem.targetGizmo.onMouseDown(e)
                e.currentTarget.targetGizmo = gizmoSystem.targetGizmo
                e.currentTarget.addEventListener("mousemove", gizmoMouseMove)
            }
        }
    }

    function onMouseUp(event) {
        if (gizmoSystem && gizmoSystem.targetGizmo) {
            gizmoSystem.targetGizmo.onMouseUp()
            event.currentTarget.removeEventListener("mousemove", gizmoMouseMove)
        }
    }

    function onClick(event) {
        if (!window.renderer)
            return
        onViewportClick(
            event,
            settings,
            engine,
            (data) => {
                DataStoreController.updateEngine({...engine, selected: data})
            })
    }

    const translate = (key) => EnglishLocalization.PROJECT.VIEWPORT[key]
    $: {
        if (isReady)
            window.renderer.miscellaneousPass.metrics.renderTarget = document.getElementById(INFORMATION_CONTAINER.FPS)
    }
    $: isSelectBoxDisabled = settings.gizmo === GIZMOS.CURSOR
</script>


<div
        on:mousedown={onMouseDown}
        on:mouseup={onMouseUp}
        on:click={onClick}
        on:dragover={e => {
        e.preventDefault()
        hovered  = true
    }}
        on:dragleave={e => {
        e.preventDefault()
        hovered  = false
    }}
        on:drop={e => {
        e.preventDefault()
        hovered  = false
        importData(e, engine)
    }}
        class={"viewport"}
        class:hovered={hovered}
>
    {#if !engine.executingAnimation}
        <ViewportSettings translate={translate} settings={settings}/>
    {/if}
    <div class="wrapper">
        <slot name="canvas"/>
        {#if isReady && !engine.executingAnimation}
            <GizmoBar translate={translate}/>
            <CameraBar translate={translate}/>
        {/if}
        {#if isReady && settings.visible.sideBarViewport}
            <SideOptions translate={translate} selectedEntity={engine.selectedEntity}/>
        {/if}
    </div>
    <div
            id={INFORMATION_CONTAINER.CONTAINER}
            class={"info-container"}
            style={"display:"  + (settings.visible.metricsViewport ? "flex" : "none")}>
        <div id={INFORMATION_CONTAINER.FPS}></div>
        <div id={INFORMATION_CONTAINER.TRANSFORMATION}></div>
    </div>


    <SelectBox
            targetElementID={RENDER_TARGET}
            disabled={isSelectBoxDisabled}
            setSelected={(_, startCoords, endCoords) => {
            if (startCoords && endCoords) {
                drawIconsToBuffer()
                const depthFBO = window.renderer.renderingPass.depthPrePass.frameBuffer
                const size = {
                    w: depthFBO.width,
                    h: depthFBO.height
                }
                const nStart = Conversion.toQuadCoord(startCoords, size)
                const nEnd = Conversion.toQuadCoord(endCoords, size)

                try {
                    const data = window.renderer.picking.readBlock(depthFBO, nStart, nEnd)
                    WORKER.postMessage({entities: window.renderer.entities, data})
                    WORKER.onmessage = ({data: selected}) => DataStoreController.updateEngine({...engine, selected })
                } catch (err) {
                    console.error(err, startCoords, nStart)
                }
            }
        }}
            target={RENDER_TARGET}
            selected={[]}
            nodes={[]}
    />
</div>

<style>
    .viewport {
        width: 100%;
        height: 100%;
        overflow: hidden;
        background-color: var(--pj-background-tertiary);
        border-radius: 5px;
        position: relative;
        display: flex;
        flex-direction: column;
    }

    .wrapper {
        display: flex;
        width: 100%;
        height: 100%;
        overflow: hidden;
    }


    .info-container {
        height: 23px;
        font-size: .7rem;
        display: flex;
        gap: 4px;
        justify-content: space-between;
        align-items: center;
        padding: 0 4px;
        background: var(--pj-background-tertiary);
        color: var(--pj-color-secondary);
    }

    .info-container > * {
        display: flex;
        gap: 4px;
        justify-content: flex-start;
        align-items: center;
    }
</style>
