// src/app/windows/project/components/blueprints/components/AttributeEditor.jsx
import React, {useContext, useMemo} from "react"
import styles from "../styles/Attribute.module.css"
import PropTypes from "prop-types"
import Material from "../templates/nodes/Material"

import {TextField} from "@f-ui/core"

import ColorPicker from "../../../../components/color/ColorPicker"
import getNodeInput from "../utils/getNodeInput"
import UpdateNodeProvider from "../context/UpdateNodeProvider"
import useLocalization from "../../../../global/useLocalization"

export default function AttributeEditor(props) {
    const selected = useMemo(() => {
        const index = props.hook.nodes.findIndex(n => (props.selected ? n.id === props.selected : n instanceof Material))
        return props.hook.nodes[index]
    }, [props.hook.selected, props.selected, props.hook.nodes])

    const {updateNode, submitNodeVariable} = useContext(UpdateNodeProvider)
    const translate = useLocalization("PROJECT", "SHADER_EDITOR")

    return (
        <div className={styles.contentWrapper}>
            <div className={styles.wrapper}>
                <TextField
                    value={selected.name} width={"100%"}
                    height={"30px"}
                    handleChange={ev => updateNode("name", ev, selected)}
                    label={translate("NAME")}
                    placeholder={translate("NAME")}
                />

                {selected.inputs
                    .map((attr, i) => !attr.accept ? (
                        <React.Fragment key={attr.label + "-attribute-" + i}>
                            {getNodeInput(attr, selected, (...attrData) => submitNodeVariable(...attrData, selected))}
                        </React.Fragment>
                    ) : null)}
                {selected.isComment ? (
                    <>
                        <label>Color</label>
                        <ColorPicker
                            submit={(_, arr) => {
                                updateNode("color", [...arr, .5], selected)
                            }}
                            value={selected.color}
                            size={"small"}
                        />
                    </>
                ) : null}
            </div>
        </div>
    )
}

AttributeEditor.propTypes = {
    selected: PropTypes.string,
    hook: PropTypes.object
}

// src/frontend/project/views/shader-editor/components/AttributeEditor.svelte
<script>

    import Input from "../../../../components/input/Input.svelte";
    import ColorPicker from "../../../../components/color-picker/ColorPicker.svelte";
    import Material from "../templates/nodes/Material";
    import Attribute from "./node/Attribute.svelte";

    export let selected
    export let nodes
    export let updateNode
    export let submitNodeVariable
    export let translate
    let selectedNode
    $: {
        const index = nodes.findIndex(n => (selected ? n.id === selected : n instanceof Material))
        selectedNode = nodes[index]
    }
</script>

{#if selectedNode}
    <div class="contentWrapper">
        <div class="wrapper">
            <Input
                    searchString={selectedNode.name}
                    width={"100%"}
                    height={"30px"}
                    setSearchString={ev => updateNode("name", ev, selectedNode)}
                    placeholder={translate("NAME")}
            />
            {#each selectedNode.inputs as attr, i}
                {#if !attr.accept}
                    <Attribute
                            attribute={attr}
                            node={selectedNode}
                            handleChange={(value, attribute) => submitNodeVariable(value, attribute, selectedNode)}
                            returnDefault={false}
                    />
                {/if}
            {/each}
            {#if selectedNode.isComment}
                <div>{translate("COLOR")}</div>
                <ColorPicker
                        submit={({r,g,b}) => {
                        updateNode("color", [r, g, b, .5], selectedNode)
                    }}
                        value={selectedNode.color}
                        size={"small"}
                />
            {/if}
        </div>
    </div>
{/if}

<style>
    .contentWrapper {
        background: var(--pj-background-tertiary);
        overflow-y: auto;
        border-bottom-left-radius: 5px;
        border-top-left-radius: 5px;
        padding: 4px;
        max-height: 100%;
        overflow-x: hidden;
        width: 250px;
    }

    .wrapper {
        overflow-x: hidden;
        color: var(--pj-color-secondary);
        width: 100%;
        display: flex;
        flex-direction: column;
        gap: 4px;
        font-size: .75rem;
    }

    .wrapper > * {
        border-radius: 3px;
        padding: 4px;
        width: 100%;
        background: var(--pj-background-primary);
    }

</style>
