// src/project/components/viewport/components/CameraBar.jsx
import styles from "../styles/SideOptions.module.css"
import {Button, Dropdown, DropdownOption, DropdownOptions, Icon, ToolTip} from "@f-ui/core"
import React, {useContext, useMemo, useState} from "react"
import {handleGrab} from "../utils/transformCamera"
import CameraGizmo from "./CameraGizmo"
import useLocalization from "../../../../global/useLocalization"
import updateCameraPlacement from "../utils/updateCameraPlacement"
import SettingsProvider from "../../../context/SettingsProvider"

export default function CameraBar() {
    const [cameraIsOrtho, setCameraIsOrtho] = useState(false)
    const cameraIcon = useMemo(() => {
        if (!cameraIsOrtho)
            return (
                <div
                    style={{width: "20px", height: "20px", perspective: "40px", transformStyle: "preserve-3d"}}>
                    <Icon
                        styles={{fontSize: "1.1rem", transform: "rotateX(45deg)"}}
                    >grid_on</Icon>
                </div>
            )
        else
            return <Icon styles={{fontSize: "1rem"}} >grid_on</Icon>
    }, [cameraIsOrtho])


    const translate = useLocalization("PROJECT", "VIEWPORT")
    const settings = useContext(SettingsProvider)
    return (
        <div className={styles.cameraWrapper} style={{right: settings.visible.sideBarViewport ? "25px" : "0"}}>
            <CameraGizmo />
            <div
                style={{
                    display: "grid",
                    gap: "2px"
                }}>
                <Dropdown
                    hideArrow={true}
                    className={styles.groupItemVert}
                >
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        Camera position
                    </ToolTip>
                    <Icon styles={{fontSize: "1.1rem"}} >videocam</Icon>
                    <DropdownOptions>
                        <DropdownOption
                            option={{
                                label: translate("TOP"),
                                onClick: () => updateCameraPlacement(0, Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("BOTTOM"),
                                onClick: () => updateCameraPlacement(0, -Math.PI /2)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("LEFT"),
                                onClick: () => updateCameraPlacement(Math.PI , 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("RIGHT"),
                                onClick: () => updateCameraPlacement(0,0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("FRONT"),
                                onClick: () =>  updateCameraPlacement(Math.PI /2, 0)
                            }}/>
                        <DropdownOption
                            option={{
                                label: translate("BACK"),
                                onClick: () =>  updateCameraPlacement(Math.PI * 1.5, 0)
                            }}/>
                    </DropdownOptions>
                </Dropdown>

                <Button
                    className={styles.groupItemVert}
                    onClick={() => {
                        const negated = !window.renderer.camera.ortho
                        window.renderer.camera.ortho = negated
                        window.renderer.camera.updateProjection()
                        setCameraIsOrtho(negated)
                    }}>
                    <ToolTip styles={{textAlign: "left", display: "grid"}}>
                        {translate("SWITCH_PROJECTION")}
                    </ToolTip>
                    {cameraIcon}
                </Button>

                <div
                    style={{
                        display: "grid",
                        transform: "translateY(12px)",
                        gap: "2px"
                    }}
                >

                    <div
                        className={[styles.groupItemVert, styles.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 0)}
                    >
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            {translate("DRAG_X_ZOOM")}
                        </ToolTip>
                        <Icon >zoom_in</Icon>
                    </div>
                    <div
                        className={[styles.groupItemVert, styles.dragInput].join(" ")}
                        onMouseDown={e => handleGrab(e, window.renderer.camera, 1)}
                        onDoubleClick={() => {
                            window.renderer.camera.centerOn = [0, 0, 0]
                            window.renderer.camera.updateViewMatrix()
                        }}>
                        <ToolTip styles={{textAlign: "left", display: "grid"}}>
                            <div>{translate("DRAG_X_DIR")}</div>
                            <div>{translate("DRAG_Y_DIR")}</div>
                            <div>{translate("DOUBLE_CLICK")}</div>
                        </ToolTip>
                        <Icon >back_hand</Icon>
                    </div>
                </div>
            </div>
        </div>
    )

}

// src/app/windows/project/components/viewport/components/CameraBar.svelte
<script>
    import {handleGrab} from "../utils/transform-camera"
    import updateCameraPlacement from "../utils/update-camera-placement"
    import {get} from "svelte/store";
    import {settingsStore} from "../../../stores/settings-store";
    import EnglishLocalization from "../../../../../static/EnglishLocalization";
    import Icon from "../../../../../components/Icon/Icon.svelte";
    import Dropdown from "../../../../../components/dropdown/Dropdown.svelte";
    import ToolTip from "../../../../../components/tooltip/ToolTip.svelte";
    import CameraGizmo from "./CameraGizmo.svelte";

    let cameraIsOrtho = false
    const translate = key => EnglishLocalization.PROJECT.VIEWPORT[key]
    const settings = get(settingsStore)
</script>

<div class={"wrapper"} style={{right: settings.visible.sideBarViewport ? "25px" : "0"}}>
    <CameraGizmo/>
    <div class="vertical-options">
        <Dropdown hideArrow={true}>
            <button  class={"item"} slot="button">
                <Icon styles={"font-size: 1.1rem"}>videocam</Icon>
                <ToolTip>
                    Camera position
                </ToolTip>
            </button>

            <button class={"item"} on:click={() => updateCameraPlacement(0, Math.PI /2)}>
                {translate("TOP")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(0, -Math.PI /2)}>
                {translate("BOTTOM")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI, 0)}>
                {translate("LEFT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(0, 0)}>
                {translate("RIGHT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI/2, 0)}>
                {translate("FRONT")}
            </button>
            <button class={"item"} on:click={() => updateCameraPlacement(Math.PI * 1.5, 0)}>
                {translate("BACK")}
            </button>
        </Dropdown>

        <button
            class={"item"}
            on:click={() => {
                const negated = !window.renderer.camera.ortho
                window.renderer.camera.ortho = negated
                window.renderer.camera.updateProjection()
                cameraIsOrtho  = negated
            }}>
            <ToolTip>
                {translate("SWITCH_PROJECTION")}
            </ToolTip>
            {#if !cameraIsOrtho}
                <div style="width: 20px; height: 20px; perspective: 40px; transform-style: preserve-3d">
                    <Icon styles="font-size: 1.1rem; transform: rotateX(45deg)">grid_on</Icon>
                </div>
            {:else}
                <Icon styles="font-size: 1rem">grid_on</Icon>
            {/if}
        </button>

        <div class="vertical-options">
            <div class={"item dragInput"} on:mousedown={e => handleGrab(e, window.renderer.camera, 0)}>
                <ToolTip styles={{textAlign: "left", display: "grid"}}>
                    {translate("DRAG_X_ZOOM")}
                </ToolTip>
                <Icon>zoom_in</Icon>
            </div>
            <div
                class={"item dragInput"}
                on:mousedown={e => handleGrab(e, window.renderer.camera, 1)}
                on:dblclick={() => {
                    window.renderer.camera.centerOn = [0, 0, 0]
                    window.renderer.camera.updateViewMatrix()
                }}>
                <ToolTip>
                    <div>{translate("DRAG_X_DIR")}</div>
                    <div>{translate("DRAG_Y_DIR")}</div>
                    <div>{translate("DOUBLE_CLICK")}</div>
                </ToolTip>
                <Icon>back_hand</Icon>
            </div>
        </div>
    </div>
</div>
