// src/app/windows/project/components/viewport/components/CameraTab.svelte
<script>
    import {settingsStore} from "../../../stores/settings-store";
    import {get} from "svelte/store";
    import Range from "../../../../../components/range/Range.svelte";
    import EnglishLocalization from "../../../../../static/EnglishLocalization";

    const toDeg = 180 / Math.PI, toRad = Math.PI / 180
    const settings = get(settingsStore)
    let state = {
        zFar: settings.zFar,
        zNear: settings.zNear,
        fov: settings.fov * toDeg,
        radius: window.renderer.camera.radius
    }

    const translate = (key) => EnglishLocalization.PROJECT.VIEWPORT[key]

</script>

<div>
    <div class={"label"}>Clipping planes</div>
    <Range
            minLabelWidth={"30px"}
            label={translate("FAR")}
            minValue={state.zNear + 1}
            variant={"embedded"}
            onFinish={(v) => {
            settings.zFar = v
            state.zFar = v
            window.renderer.camera.zFar = v
            window.renderer.camera.updateProjection()
        }}
            value={state.zFar}
            handleChange={v => state.zFar = v}
    />
    <Range
            minLabelWidth={"30px"}
            label={translate("NEAR")}
            variant={"embedded"}
            maxValue={state.zFar - 1}
            onFinish={(v) => {
                settings.zNear = v
                state.zNear = v
                window.renderer.camera.zNear = v
                window.renderer.camera.updateProjection()
            }}
            value={state.zNear}
            handleChange={v => state.zNear = v}
    />

    <div class={"label"}>Field of view</div>
    <Range
            minLabelWidth={"30px"}
            label={translate("FOV")}
            minValue={10}
            maxValue={110}
            disabled={settings.ortho}
            variant={"embedded"}
            onFinish={(v) => {
            settings.fov = v * toRad
            state.fov = v
            window.renderer.camera.fov = v * toRad
            window.renderer.camera.updateProjection()
        }}
            value={state.fov}
            handleChange={v => state.fov = v}
    />
    <Range
            label={translate("ZOOM")}
            onFinish={(v) => {
            settings.radius = v
            state.radius = v
            window.renderer.camera.radius = v
            window.renderer.camera.updateViewMatrix()
        }}
            hideValue={true}
            value={state.radius}
            handleChange={v => {
            state.radius = v
            window.renderer.camera.radius = v
            window.renderer.camera.updateViewMatrix()
        }}
    />
</div>

// src/project/components/viewport/components/CameraTab.jsx
import useDirectState from "../../../../components/hooks/useDirectState"
import React, {useContext} from "react"
import SettingsProvider from "../../../context/SettingsProvider"
import styles from "../../component/styles/Forms.module.css"
import Range from "../../../../components/range/Range"
import useLocalization from "../../../../global/useLocalization"

const toDeg = 180 / Math.PI, toRad = Math.PI / 180
export default function CameraTab() {
    const settings = useContext(SettingsProvider)
    const [state] = useDirectState({
        zFar: settings.zFar,
        zNear: settings.zNear,
        fov: settings.fov * toDeg,
        radius: window.renderer.camera.radius
    })

    const translate = useLocalization("PROJECT", "VIEWPORT")

    return (
        <>
            <label className={styles.label}>Clipping planes</label>
            <Range
                minLabelWidth={"30px"}
                label={translate("FAR")}
                minValue={state.zNear + 1}
                variant={"embedded"}
                onFinish={(v) => {
                    settings.zFar = v
                    state.zFar = v
                    window.renderer.camera.zFar = v
                    window.renderer.camera.updateProjection()
                }}
                value={state.zFar}
                handleChange={v => state.zFar = v}
            />
            <Range
                minLabelWidth={"30px"}
                label={translate("NEAR")}
                variant={"embedded"}
                maxValue={state.zFar - 1}
                onFinish={(v) => {
                    settings.zNear = v
                    state.zNear = v
                    window.renderer.camera.zNear = v
                    window.renderer.camera.updateProjection()
                }}
                value={state.zNear}
                handleChange={v => state.zNear = v}
            />


            <label className={styles.label}>Field of view</label>
            <Range
                minLabelWidth={"30px"}
                label={translate("FOV")}
                minValue={10}
                maxValue={110}
                disabled={settings.ortho}
                variant={"embedded"}
                onFinish={(v) => {
                    settings.fov = v * toRad
                    state.fov = v
                    window.renderer.camera.fov = v * toRad
                    window.renderer.camera.updateProjection()
                }}
                value={state.fov}
                handleChange={v => state.fov = v}
            />
            <Range
                label={translate("ZOOM")}
                onFinish={(v) => {
                    settings.radius = v
                    state.radius = v
                    window.renderer.camera.radius = v
                    window.renderer.camera.updateViewMatrix()
                }}
                hideValue={true}
                value={state.radius}
                handleChange={v => {
                    state.radius = v
                    window.renderer.camera.radius = v
                    window.renderer.camera.updateViewMatrix()
                }}
            />

        </>
    )
}
