// src/frontend/editor/views/shader-editor/components/node/Comment.svelte
<script>
    import KEYS from "../../../../../../../public/engine/production/data/KEYS";
    import dragNode from "../../utils/drag-node";
    import SelectionStore from "../../../../stores/SelectionStore";

    export let submitName
    export let node
    export let selected
    export let setSelected
    export let canvas
    let ref

    $: isSelected =  selected.indexOf(node.id) > -1

    const handleDragStart = (event) => {
        if (event.button !== 0)
            return
        if (!SelectionStore.map.get(node.id))
            setSelected(node.id, event.ctrlKey)
        dragNode(event, ref.parentNode)
    }

    let onEdit = false
    let nameCache = node.name
    $: rgb = node.color.slice(0, 3).join(", ")

</script>

<g bind:this={ref} transform={`translate(${node.x} ${node.y})`}>
    <foreignObject

            data-group={node.id}
            id={node.id}
            class="wrapper"
            style={("background:" + node.color ? `rgba(${rgb}, .5);` : "rgba(150, 150, 150, .5);") + `outline-color: ${isSelected ? "yellow" : "unset"}`}
            width="{node.width}"
            height="{node.height}">
        {#if onEdit}
            <input
                    style={`background: rgb(${rgb})`}
                    value={nameCache}
                    on:change={v => nameCache = v.target.value}
                    class="input"
                    on:blur={() => {
                submitName(nameCache)
                onEdit = false
            }}
                    on:keydown={(e) => {
                if (e.key === KEYS.Enter) {
                    submitName(nameCache)
                    onEdit = false
                }
            }}
            />
        {:else}
            <div
                    class="header"
                    style={`background: rgb(${rgb})`}
                    id={node.id + "-node"}
                    on:doubleclick={() => onEdit = true}
            >
                {node.name}
            </div>
        {/if}
    </foreignObject>
</g>


<style>
    .wrapper {
        border-radius: 3px;
        outline: transparent 2px solid;
        resize: both;
    }

    .header {
        width: 100%;

        height: 35px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        font-size: .8rem;
        font-weight: 550;
        padding: 4px;

        color: var(--pj-color-secondary);
        cursor: grab;
    }

    .wrapper:active {
        cursor: grabbing;
    }

    .input {
        height: 35px;
        width: 100%;
        background: none;
        border: none;
        outline: none;

        color: var(--pj-color-secondary);
    }
</style>

// src/app/windows/project/components/blueprints/components/node/Comment.jsx
import PropTypes from "prop-types"
import styles from "../../styles/Comment.module.css"
import React, {useMemo, useState} from "react"
import useComment from "../../hooks/useComment"
import KEYS from "../../../../engine/data/KEYS"

export default function Comment(props) {
    const [onEdit, setOnEdit] = useState(false)
    const [nameCache, setNameCache] = useState(props.node.name)
    const {ref, selected} = useComment(props)
    const rgb = useMemo(() => props.node.color.slice(0, 3).join(", "), [props.node])
    return (
        <g
            ref={ref}
            transform={`translate(${props.node.x} ${props.node.y})`}
        >
            <foreignObject
                onContextMenu={() => props.setSelected(props.node.id)}
                data-group={props.node.id}
                id={props.node.id}

                className={styles.wrapper}
                data-seleted={`${selected}`}
                style={{
                    background: props.node.color ? `rgba(${rgb}, .5)` : "rgba(150, 150, 150, .5)",
                    width: props.node.width + "px",
                    height: props.node.height + "px"
                }}>
                {onEdit ? <input
                    style={{background: `rgb(${rgb})`}}
                    value={nameCache}
                    onChange={v => setNameCache(v.target.value)}
                    className={styles.input}
                    onBlur={() => {
                        props.submitName(nameCache)
                        setOnEdit(false)
                    }}
                    onKeyDown={(e) => {
                        if (e.key === KEYS.Enter) {
                            props.submitName(nameCache)
                            setOnEdit(false)
                        }
                    }}
                /> : <div
                    className={styles.header}
                    style={{background: `rgb(${rgb})`}}
                    id={props.node.id + "-node"}
                    onDoubleClick={() => setOnEdit(true)}
                >
                    {props.node.name}
                </div>}
            </foreignObject>
        </g>
    )
}
Comment.propTypes = {
    submitName: PropTypes.func,
    node: PropTypes.object.isRequired,
    selected: PropTypes.array,
    setSelected: PropTypes.func,
}
