// src/app/windows/project/views/shader-editor/components/node/Input.svelte
<script>
    import linkNodes from "../../utils/link-nodes"
    import getNodeInput from "../../utils/get-node-input"

    export let handleLink
    export let attribute
    export let inputLinks
    export let onDrag
    export let node
    export let submitNodeVariable


    let wrapperRef
    $: link = attribute.accept ? inputLinks.find(o => o.targetKey === attribute.key)

</script>
<div
        data-link={link ? (link.target + "-" + link.source) : null}
        class="attribute"
        bind:this={wrapperRef}
        data-dtype={"input"}
        data-disabled={`${attribute.disabled || attribute.type === DATA_TYPES.UNDEFINED && (inputLinks.length === 0 && node.inputs.length > 0)}`}
        style={{transform: attribute.accept ? "translateX(var(--direction))" : undefined}}
>

    {#if attribute.accept}
        <div
            id={node.id + attribute.key}
            class="connection"
            data-dtype={"input"}
            data-disabled={`${attribute.disabled || attribute.type === DATA_TYPES.UNDEFINED && (inputLinks.length === 0 && node.inputs.length > 0)}`}
            data-highlight={link ? "-" : undefined}
            on:drop={e => {
                e.preventDefault()
                onDrag.setDragType(undefined)
                if (!attribute.disabled)
                    linkNodes(e, attribute, node, handleLink)
            }}></div>
    {/if}
    {#if link}
        {attribute.label}
        {:else}
        {getNodeInput(attribute, node, (...attrData) => submitNodeVariable(...attrData, node), true)}
    {/if}
</div>

// src/app/windows/project/components/blueprints/components/node/Input.jsx
import styles from "../../styles/Node.module.css"
import PropTypes from "prop-types"
import {DATA_TYPES} from "../../../../engine/data/DATA_TYPES"
import React, {useContext, useMemo, useRef} from "react"
import OnDragProvider from "../../context/DragProvider"
import NodeProvider from "../../context/NodeProvider"
import linkNodes from "../../utils/linkNodes"
import getNodeInput from "../../utils/getNodeInput"
import UpdateNodeProvider from "../../context/UpdateNodeProvider"

export default function Input(props) {
    const {handleLink, inputLinks, attribute} = props
    const {submitNodeVariable} = useContext(UpdateNodeProvider)
    const node = useContext(NodeProvider)
    const onDragContext = useContext(OnDragProvider)

    const wrapperRef = useRef()
    const link = useMemo(
        () => attribute.accept ? inputLinks.find(o => o.targetKey === attribute.key) : undefined,
        [inputLinks]
    )


    return (
        <div
            data-link={link ? (link.target + "-" + link.source) : null}
            className={styles.attribute} ref={wrapperRef}
            data-dtype={"input"}
            data-disabled={`${attribute.disabled || attribute.type === DATA_TYPES.UNDEFINED && (inputLinks.length === 0 && node.inputs.length > 0)}`}
            style={{transform: attribute.accept ? "translateX(var(--direction))" : undefined}}
        >

            {attribute.accept ? (
                <div
                    id={node.id + attribute.key}
                    className={styles.connection}
                    data-dtype={"input"}
                    data-disabled={`${attribute.disabled || attribute.type === DATA_TYPES.UNDEFINED && (inputLinks.length === 0 && node.inputs.length > 0)}`}
                    data-highlight={link ? "-" : undefined}
                    onDrop={e => {
                        e.preventDefault()
                        onDragContext.setDragType(undefined)
                        if (!attribute.disabled)
                            linkNodes(e, attribute, node, handleLink)
                    }}
                />
            ) : null}
            {link ? attribute.label : getNodeInput(attribute, node, (...attrData) => submitNodeVariable(...attrData, node), true)}
        </div>
    )
}


Input.propTypes = {
    handleLink: PropTypes.func,
    attribute: PropTypes.object.isRequired,
    inputLinks: PropTypes.arrayOf(PropTypes.object).isRequired
}
