// src/app/windows/project/views/shader-editor/components/node/Node.svelte
<script>
    import LINK_WIDTH from "../../data/LINK_WIDTH";
    import NODE_TYPES from "../../data/NODE_TYPES";
    import NODE_INFO from "../../data/NODE_INFO";
    import getBezierCurve from "../../utils/get-bezier-curve";
    import dragNode from "../../utils/drag-node";
    import {onDestroy, onMount} from "svelte";
    import NodeInput from "./NodeInput.svelte";
    import NodeOutput from "./NodeOutput.svelte";
    import Material from "../../templates/nodes/Material";
    import SelectionStore from "../../../../stores/SelectionStore";
    import ShaderEditorController from "../../ShaderEditorController";

    export let links
    export let node
    export let handleLink
    export let selected
    export let setSelected
    export let submitNodeVariable
    export let canvas
    export let onDrag
    let pathRef
    let ref

    $: isSelected = selected.indexOf(node.id) > -1


    let outputLinks
    let inputLinks
    $: {
        const out = [], inp = []
        links.forEach(l => {
            if (l.source && l.source.includes(node.id))
                out.push(l)
            if (l.target && l.target.includes(node.id))
                inp.push(l)
        })
        outputLinks = out
        inputLinks = inp
    }

    let nodeInfo
    $: {
        let key = (Object.entries(NODE_TYPES).find(([, value]) => value === node.type))
        if (key)
            nodeInfo = key[0]
        nodeInfo = NODE_INFO[key] ? NODE_INFO[key] : {}
    }
    const handleLinkDrag = (event, draggableElement) => {
        const scale = ShaderEditorController.scale
        const parent = ref?.parentNode.parentNode
        const bBox = draggableElement.getBoundingClientRect()
        let parentBBox = parent.getBoundingClientRect()
        const bounding = {
            x: parent.scrollLeft - parentBBox.left,
            y: parent.scrollTop - parentBBox.top
        }

        const curve = getBezierCurve(
            {
                x: (bBox.x + bounding.x + 7.5) / scale,
                y: (bBox.y + bounding.y + 7.5 + LINK_WIDTH * 2) / scale
            },
            {
                x1: (event.clientX + bounding.x + 7.5) / scale,
                y1: (event.clientY + bounding.y + 7.5 + LINK_WIDTH * 2) / scale
            })

        pathRef?.setAttribute("d", curve)
    }

    const handleDragStart = (event) => {
        if (event.button !== 0)
            return
        if (!SelectionStore.map.get(node.id))
            setSelected(node.id, event.ctrlKey)
        dragNode(event, ref, ref.parentNode.parentNode)
    }


    $: {
        let width
        switch (node.size) {
            case 0:
                width = "225px"
                break
            case 1:
                width = "175px"
                break
            default:
                width = "150px"
                break
        }

        if (ref) {
            ref.firstChild.setAttribute("height", `0`)
            setTimeout(() => {
                const h = ref.firstChild.scrollHeight + 4
                ref.firstChild.setAttribute("height", `${h >= 35 ? h : 55}`)
                ref.firstChild.setAttribute("width", `${width}`)
            }, 0)
        }
    }
</script>

<g>
    <g
            bind:this={ref}
            data-ismaterial="{node instanceof Material}"
            transform={`translate(${node.x} ${node.y})`}
    >
        <foreignObject
                data-node={node.canBeDeleted ? node.id : undefined}
                id={node.id}
                class="wrapper"
                style={isSelected ? "outline: yellow 2px solid" : undefined}
        >
            <div
                    class="label"
                    style="border-color: {nodeInfo.COLOR}"
                    id={node.id + "-node"}
                    on:mousedown={handleDragStart}
            >
                {node.name}
            </div>
            <div class="content" on:click={event => setSelected(node.id, event.ctrlKey)}>
                <div
                        class="column"
                        style={node.output.length > 0  ? `max-width: 75%; width: 75%;` : "width: 100%"}>
                    {#each node.inputs as a, i}
                        <NodeInput
                                handleLink={handleLink}
                                attribute={a}
                                node={node}
                                inputLinks={inputLinks}
                                submitNodeVariable={submitNodeVariable}
                        />
                    {/each}
                </div>
                {#if node.output.length > 0}
                    <div
                            class="column"
                            style="justify-content: flex-end; max-width:75%"
                    >
                        {#each node.output as a, i}
                            <NodeOutput
                                    onDragEnd={() => pathRef.setAttribute("d", undefined)}
                                    data={a}
                                    node={node}
                                    onDrag={onDrag}
                                    handleLinkDrag={handleLinkDrag}
                                    inputLinks={inputLinks}
                                    outputLinks={outputLinks}
                            />
                        {/each}
                    </div>
                {/if}
            </div>
        </foreignObject>
    </g>
    <path
            bind:this={pathRef}
            fill={"none"}
            stroke={"var(--pj-accent-color)"}
            stroke-width={LINK_WIDTH}
            stroke-dasharray={"3,3"}
            d=""></path>
</g>

<style>
    .wrapper {
        overflow: visible;
        box-shadow: var(--pj-boxshadow);
        background: var(--pj-background-secondary);
        transition: outline 150ms linear;
        outline: transparent 2px solid;
        position: relative;
        border-radius: 3px;
        min-height: 35px;
        border: var(--pj-border-primary) 1px solid;
    }


    .label {
        cursor: grab;
        height: 30px;
        display: flex;
        border-radius: 3px 3px 0 0;
        align-items: center;
        gap: 3px;
        padding: 0 4px;
        font-weight: 550;
        font-size: 0.7rem;
        color: var(--pj-color-secondary);
        border-left: transparent 3px solid;
        background: var(--pj-background-primary);
        border-bottom: var(--pj-border-primary) 1px solid;
        transition: color 150ms linear;
    }

    .label:active {
        cursor: grabbing;
    }

    .content {
        display: flex;
        height: calc(100% - 30px);
        overflow: visible;
        border-radius: 0 0 3px 3px;
        background-color: var(--pj-background-primary);
        justify-content: space-between;
    }

</style>

// src/app/windows/project/components/blueprints/components/node/Node.jsx
import PropTypes from "prop-types"
import styles from "../../styles/Node.module.css"
import React from "react"
import useNode from "../../hooks/useNode"
import LINK_WIDTH from "../../data/LINK_WIDTH"
import Input from "./Input"
import Output from "./Output"
import NodeProvider from "../../context/NodeProvider"

export default function Node(props) {
    const {
        nodeInfo, width,
        ref, handleLinkDrag,
        height, pathRef,
        outputLinks,
        inputLinks,
        selected
    } = useNode(
        props.selected,
        props.setSelected,
        props.node,
        props.links
    )


    return (
        <NodeProvider.Provider value={props.node}>
            <g>
                <g
                    ref={ref}
                    transform={`translate(${props.node.x} ${props.node.y})`}
                >
                    <foreignObject
                        data-node={props.node.canBeDeleted ? props.node.id : undefined}
                        id={props.node.id}
                        onMouseDown={(e) => props.setSelected(props.node.id, e.ctrlKey)}
                        className={styles.wrapper}
                        style={{
                            width: width,
                            height: height + "px",
                            outline: selected ? "yellow 2px solid" : undefined
                        }}
                    >
                        <div
                            className={styles.label}
                            style={{borderColor: nodeInfo.COLOR}}
                            id={props.node.id + "-node"}
                            title={nodeInfo.LABEL}
                        >
                            {props.node.name}
                        </div>
                        <div className={styles.content}>
                            <div className={styles.column} style={{maxWidth: props.node.output.length > 0  ? `calc(${width} - 75px)` : undefined}}>
                                {props.node.inputs.map((a, i) => (
                                    <React.Fragment key={a.key + "-input-" + i}>
                                        <Input
                                            handleLink={props.handleLink}
                                            attribute={a}
                                            inputLinks={inputLinks}
                                        />
                                    </React.Fragment>
                                ))}
                            </div>
                            {props.node.output.length > 0 ?
                                <div
                                    className={styles.column}
                                    style={{justifyContent: "flex-end", width: "50%"}}
                                >
                                    {props.node.output.map((a, i) => (
                                        <React.Fragment key={a.key + "-output-" + i}>
                                            <Output
                                                onDragEnd={() => pathRef.current.setAttribute("d", undefined)}
                                                data={a}
                                                handleLinkDrag={handleLinkDrag}
                                                inputLinks={inputLinks}
                                                outputLinks={outputLinks}
                                            />
                                        </React.Fragment>
                                    ))}
                                </div>
                                :
                                null
                            }
                        </div>
                    </foreignObject>
                </g>
                <path
                    ref={pathRef}
                    fill={"none"}
                    stroke={"var(--pj-accent-color)"}
                    strokeWidth={LINK_WIDTH}
                    strokeDasharray={"3,3"}
                />
            </g>
        </NodeProvider.Provider>
    )
}
Node.propTypes = {
    links: PropTypes.array,
    node: PropTypes.object.isRequired,
    handleLink: PropTypes.func,
    selected: PropTypes.array,
    setSelected: PropTypes.func
}
