// src/project/components/viewport/wrapper/Viewport.jsx
import PropTypes from "prop-types"
import styles from "./styles/Viewport.module.css"
import React, {useContext, useEffect, useId, useMemo} from "react"
import useContextTarget from "../../../../components/context/hooks/useContextTarget"
import RENDER_TARGET from "../../../../static/misc/RENDER_TARGET"
import ViewportOptions from "../options/ViewportOptions"
import COMPONENTS from "../../../engine/templates/COMPONENTS"
import Picking from "../../../engine/systems/misc/Picking"
import SelectBox from "../../../../components/select-box/SelectBox"
import Conversion from "../../../engine/utils/Conversion"
import GIZMOS from "../../../../static/misc/GIZMOS"
import SettingsProvider from "../../../providers/SettingsProvider"
import Transformation from "../../../engine/utils/Transformation"
import importData from "../../../utils/importer/import"
import getOptionsViewport from "./hooks/getOptionsViewport"
import Constructor from "../../../engine/Constructor"
import DevelopmentRenderer from "../../../engine-extension/DevelopmentRenderer"
import ViewportSideBar from "../side-bar/ViewportSideBar"

const TRIGGERS = ["data-viewport"]
const MAX_TIMESTAMP = 350, MAX_DELTA = 50, LEFT_BUTTON = 0
const WORKER = new Worker(new URL("./hooks/findEntities.js", import.meta.url))
export default function Viewport(props) {
    const renderer = window.renderer
    const settings = useContext(SettingsProvider)
    const internalID = useId()

    const optionsViewport = useMemo(
        () => getOptionsViewport(props.engine, props.utils),
        [props.engine.selectedEntity, props.utils.toCopy]
    )
    useEffect(() => {
        Constructor(document.getElementById(RENDER_TARGET), settings.resolution, DevelopmentRenderer)
        props.engine.setViewportInitialized(true)
    }, [])


    function pickIcon (cameraMesh, pickSystem, camera, coords){
        return pickSystem.pickElement((shader, proj) => {
            const entities = renderer.entities
            for (let m = 0; m < entities.length; m++) {
                const currentInstance = entities[m]
                if (entities[m].active) {
                    let t = currentInstance.components[COMPONENTS.TRANSFORM]?.transformationMatrix
                    if(!t)
                        t = currentInstance.components[COMPONENTS.DIRECTIONAL_LIGHT]?.transformationMatrix
                    if (t && !currentInstance.components[COMPONENTS.MESH])
                        Picking.drawMesh(currentInstance.components[COMPONENTS.CAMERA] ? cameraMesh : pickSystem.mesh, currentInstance, camera.viewMatrix, proj, t, shader)
                }
            }
        }, {x: coords[0], y: coords[1]}, camera)
    }

    function pickMesh(meshesMap, x, y){
        const w =  window.gpu.canvas.width, h =  window.gpu.canvas.height
        const coords = Conversion.toQuadCoord({x, y}, {w, h})
        const picked = renderer.picking.depthPick(renderer.renderingPass.depthPrePass.frameBuffer, coords)
        return Math.round((picked[1] + picked[2])* 255)
    }

    function handler(event) {
        if(settings.gizmo !== GIZMOS.CURSOR) {
            const deltaX = Math.abs(event.currentTarget.startedCoords.x - event.clientX)
            const deltaY = Math.abs(event.currentTarget.startedCoords.y - event.clientY)
            const elapsed = (performance.now() - event.currentTarget.started)

            if (window.gpu.canvas === event.target && elapsed <= MAX_TIMESTAMP && deltaX < MAX_DELTA && deltaY < MAX_DELTA) {
                const camera = renderer.camera
                const p = renderer.picking
                const cameraMesh = renderer.editorSystem.billboardSystem.cameraMesh
                const meshesMap = renderer.data.meshesMap
                const target = event.currentTarget.getBoundingClientRect()
                const coords = [event.clientX - target.left, event.clientY - target.top]

                let picked = pickIcon( cameraMesh, p, camera, coords)
                if (!picked)
                    picked = pickMesh(meshesMap, event.clientX, event.clientY)
                if (picked > 0) {
                    const entity = renderer.entities.find(e => e.components[COMPONENTS.PICK]?.pickIndex === picked)
                    if (entity) props.engine.setSelected(prev => {
                        const i = prev.findIndex(e => e === entity.id)
                        if (i > -1) {
                            prev.splice(i, 1)
                            return prev
                        }
                        if (event.ctrlKey) return [...prev, entity.id]
                        else return [entity.id]
                    })
                } else
                    props.engine.setSelected([])
            }
        }else
            event.currentTarget.started = undefined
    }
    function updateCursor(coords){
        const t = renderer.cursor.components[COMPONENTS.TRANSFORM]
        t.translation = coords
        t.transformationMatrix = Transformation.transform(t.translation, [0,0,0,1], t.scaling)
    }
    let latestTranslation
    function handleMouse(e){
        if(e.type === "mousemove"){
            latestTranslation =  Conversion.toScreen(e.clientX, e.clientY, renderer.camera).slice(0, 3)
            updateCursor(latestTranslation)
        }
        else
            document.removeEventListener("mousemove", handleMouse)
    }

    useContextTarget(internalID, optionsViewport, TRIGGERS)

    return (
        <>
            {props.engine.executingAnimation ? null : <ViewportOptions/>}
            <div
                onMouseDown={e => {
                    e.currentTarget.started = performance.now()
                    e.currentTarget.startedCoords = {x: e.clientX, y: e.clientY}
                    if(e.button === LEFT_BUTTON && settings.gizmo === GIZMOS.CURSOR && e.target === window.gpu.canvas || e.target === e.currentTarget){
                        latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera, renderer.cursor.components[COMPONENTS.TRANSFORM].translation).slice(0, 3)
                        updateCursor(latestTranslation)
                        document.addEventListener("mousemove", handleMouse)
                        document.addEventListener("mouseup", handleMouse, {once: true})
                    }
                }}
                onClick={handler}
                onDragOver={e => {
                    if (props.allowDrop) {
                        e.preventDefault()
                        e.currentTarget.classList.add(styles.hovered)
                    }
                }}
                onDragLeave={e => {
                    e.preventDefault()
                    e.currentTarget.classList.remove(styles.hovered)
                }}
                onDrop={e => {
                    // TODO - APPLY MATERIAL BY DROPPING IT ON MESH (PICK MESH AND LOAD MATERIAL)
                    if (props.allowDrop) {
                        e.preventDefault()
                        e.currentTarget.classList.remove(styles.hovered)
                        importData(e,  props.engine)
                    }
                }}
   
                data-viewport={RENDER_TARGET}
                id={internalID}
                className={styles.viewport}
            >
                <canvas 
                    id={RENDER_TARGET} 
                    style={{width: "100%", height: "100%", background: "transparent"}}
                    width={settings.resolution[0]}
                    height={settings.resolution[1]}
                />
                <ViewportSideBar engine={props.engine}/>
                <SelectBox
                    disabled={settings.gizmo === GIZMOS.CURSOR}
                    setSelected={(_, startCoords, endCoords) => {
                        if(startCoords && endCoords) {
                            const depthFBO = renderer.renderingPass.depthPrePass.frameBuffer
                            const size = {
                                w: depthFBO.width,
                                h: depthFBO.height
                            }
                            const nStart = Conversion.toQuadCoord(startCoords, size)
                            const nEnd = Conversion.toQuadCoord(endCoords, size)

                            try{
                                const data = renderer.picking.readBlock(depthFBO, nStart, nEnd)
                                WORKER.postMessage({entities: renderer.entities, data})
                                WORKER.onmessage = ({data: selected}) => props.engine.setSelected(selected)
                            }catch (err){
                                console.error(err, startCoords, nStart)
                            }
                        }
                    }}
                    target={RENDER_TARGET}
                    selected={[]}
                    nodes={[]}
                />
            </div>
        </>
    )
}

Viewport.propTypes = {
    utils: PropTypes.object,
    allowDrop: PropTypes.bool.isRequired,
    executingAnimation: PropTypes.bool,
    engine: PropTypes.object,
    id: PropTypes.string
}

// src/app/windows/project/components/viewport/Viewport.svelte
<script>
    import RENDER_TARGET from "../../static/misc/RENDER_TARGET"
    import GIZMOS from "../../static/misc/GIZMOS"
    import importData from "../../libs/importer/import"
    import updateCursor from "./utils/update-cursor"
    import onViewportClick from "./utils/on-viewport-click"
    import {getContext, onMount} from "svelte";
    import ContextMap from "../../static/misc/ContextMap";
    import EditorEngine from "../../libs/engine-extension/EditorEngine";
    import windowBuilder from "../../libs/engine/window-builder";
    import Conversion from "../../libs/engine/utils/Conversion";
    import {effect} from "../../libs/effect";

    import {engine as engineStore} from "../../stores/engine-store";
    import {get} from "svelte/store";
    import {settingsStore} from "../../stores/settings-store";
    import entitySearchWorker from "../../../../web-workers/entity-search-worker";

    export let utils = {}
    const LEFT_BUTTON = 0
    const renderer = window.renderer
    let WORKER = entitySearchWorker

    const engine = get(engineStore),
        settings = get(settingsStore),
        id = sessionStorage.getItem("electronWindowID")

    let gizmoSystem
    let rendererIsReady = false
    let canvasRef

    $: {
        if (canvasRef && !engine.viewportInitialized) {
            windowBuilder(canvasRef)
            engineStore.set({...engine, viewportInitialized: true})

            window.renderer = new EditorEngine({w: settings.resolution[0], h: settings.resolution[1]})
            rendererIsReady = true
        }
    }
    let latestTranslation

    function handleMouse(e) {
        if (e.type === "mousemove") {
            latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera).slice(0, 3)
            updateCursor(latestTranslation)
        } else
            document.removeEventListener("mousemove", handleMouse)
    }

    function gizmoMouseMove(event) {
        if (gizmoSystem && gizmoSystem.targetGizmo)
            gizmoSystem.targetGizmo.onMouseMove(event)
    }

    function onMouseDown(e) {
        if (!window.renderer)
            return
        e.currentTarget.startedCoords = {x: e.clientX, y: e.clientY}
        if (e.button === LEFT_BUTTON && settings.gizmo === GIZMOS.CURSOR && e.target === window.gpu.canvas || e.target === e.currentTarget) {
            latestTranslation = Conversion.toScreen(e.clientX, e.clientY, renderer.camera, renderer.cursor.components[COMPONENTS.TRANSFORM].translation).slice(0, 3)
            updateCursor(latestTranslation)
            document.addEventListener("mousemove", handleMouse)
            document.addEventListener("mouseup", handleMouse, {once: true})
        }
        if (e.button === LEFT_BUTTON && settings.gizmo !== GIZMOS.CURSOR) {
            gizmoSystem = window.renderer.editorSystem.gizmoSystem
            if (gizmoSystem.targetGizmo) {
                gizmoSystem.targetGizmo.onMouseDown(e)
                e.currentTarget.targetGizmo = gizmoSystem.targetGizmo
                e.currentTarget.addEventListener("mousemove", gizmoMouseMove)
            }
        }
    }

    function onMouseUp(event) {
        if (gizmoSystem && gizmoSystem.targetGizmo) {
            gizmoSystem.targetGizmo.onMouseUp()
            event.currentTarget.removeEventListener("mousemove", gizmoMouseMove)
        }
    }

    function onClick(event) {
        if (!window.renderer)
            return
        onViewportClick(event, settings, engine, (data) => {
            engineStore.set(data)
        })
    }
</script>


<div
        on:mousedown={onMouseDown}
        on:mouseup={onMouseUp}
        on:click={onClick}

        on:dragover={e => {
            e.preventDefault()
            //e.currentTarget.classList.add("hovered")
        }}
        on:dragleave={e => {
            e.preventDefault()
            //e.currentTarget.classList.remove("hovered")
        }}
        on:drop={e => {
            e.preventDefault()
    //        e.currentTarget.classList.remove("hovered")
            importData(e, engine)
        }}
        class={"viewport"}
>
    {#if !engine.executingAnimation}
        <div></div>
        <!--        <HeaderOptions/>-->
    {/if}
    <div style="display: flex; width: 100%; height: 100%; overflow: hidden">
        <canvas
                bind:this={canvasRef}
                id={RENDER_TARGET}
                style="width: {settings.visible.sideBarViewport ? "calc(100% - 23px)" : "100%"}; height: 100%; background: transparent"
            width={settings.resolution[0]}
            height={settings.resolution[1]}
        >

        </canvas>
        {#if rendererIsReady && !engine.executingAnimation}
            <div></div>
            <!--<GizmoBar/>-->
            <!--<CameraBar/>-->
        {/if}
        {#if rendererIsReady && settings.visible.sideBarViewport}
            <div></div>
            <!--            <SideOptions selectedEntity={engine.selectedEntity}/>-->
        {/if}
    </div>
    {#if rendererIsReady}
        <div></div>
        <!--        <Information visible={settings.visible.metricsViewport}/>-->
    {/if}

    <!--    <SelectBox-->
    <!--            targetElementID={RENDER_TARGET}-->
    <!--            disabled={settings.gizmo === GIZMOS.CURSOR}-->
    <!--            setSelected={(_, startCoords, endCoords) => {-->
    <!--            if (startCoords && endCoords) {-->
    <!--                drawIconsToBuffer()-->
    <!--                const depthFBO = renderer.renderingPass.depthPrePass.frameBuffer-->
    <!--                const size = {-->
    <!--                    w: depthFBO.width,-->
    <!--                    h: depthFBO.height-->
    <!--                }-->
    <!--                const nStart = Conversion.toQuadCoord(startCoords, size)-->
    <!--                const nEnd = Conversion.toQuadCoord(endCoords, size)-->

    <!--                try {-->
    <!--                    const data = renderer.picking.readBlock(depthFBO, nStart, nEnd)-->
    <!--                    entityWorker.postMessage({entities: renderer.entities, data})-->
    <!--                    entityWorker.onmessage = ({data: selected}) => engine.setSelected(selected)-->
    <!--                } catch (err) {-->
    <!--                    console.error(err, startCoords, nStart)-->
    <!--                }-->
    <!--            }-->
    <!--        }}-->
    <!--            target={RENDER_TARGET}-->
    <!--            selected={[]}-->
    <!--            nodes={[]}-->
    <!--    />-->
</div>
